questionnaire_party_answers = {
    0: {
        "CDU/CSU": "The CDU/CSU supports increasing resources to assist Ukraine, emphasizing a strong stance against Russia's aggression and supporting Ukraine's defense capabilities. They backed efforts such as the \"Sonderverm\u00f6gen\" to bolster Germany's defense and aid Ukraine. Their position reflects a commitment to sustained military and financial support while balancing domestic defense readiness.",
        "SPD": "The SPD supports continued military and financial assistance to Ukraine but emphasizes a realistic approach due to the strain on Germany's own defense capabilities. It stresses the importance of international coordination, particularly at the European level, to ensure effective and sustainable support. Examples include providing advanced weapons like IRIS-T air defense systems and working with industrial partners to replenish Bundeswehr stocks while supporting Ukraine's defense modernization.",
        "FDP": "The FDP has consistently advocated for a balanced approach to supporting Ukraine. In line with its historical stance, the FDP likely supports enhanced military and financial aid for Ukraine as part of ensuring European security and showing solidarity against Russian aggression. They also emphasize the importance of developing a long-term strategy to strengthen Germany's and Europe\u2019s defensive capabilities while considering fiscal responsibility.",
        "GRUENE": "The Green Party (*B\u00fcndnis 90/Die Gr\u00fcnen*) is a strong advocate for increased support to Ukraine, emphasizing both military and financial assistance. They argue that Germany must enhance its efforts to strengthen Ukraine's defense capabilities and develop a long-term strategy for support. This reflects their broader stance on solidarity with Ukraine, European peace, and countering Russian aggression.",
        "LINKE": "Die LINKE has consistently opposed increased military support for Ukraine. The party generally advocates for de-escalation, diplomacy, and a focus on humanitarian aid rather than military intervention. They argue that further militarization risks prolonging the conflict and escalating tensions.",
        "AFD": "The Alternative for Germany (AfD) generally opposes increased support for Ukraine, including financial and military aid. The party has consistently criticized Germany's involvement in the conflict, arguing that such actions harm German interests and economic stability. Their position typically emphasizes diplomatic solutions and prioritizing domestic issues over foreign military engagements."
    },
    1: {
        "CDU/CSU": "The CDU/CSU has expressed consistent support for increasing the budget of the Bundeswehr, citing that the current funding, including the \u20ac100 billion special fund from the \"Zeitenwende\" initiative, is insufficient to address the military's significant deficiencies. Roderich Kiesewetter, the CDU's foreign policy spokesperson, criticized the slow implementation of the defense reforms and underlined that the Bundeswehr had \"lost a year\" and remains inadequately prepared compared to early 2022. The CDU/CSU continues to advocate for additional budgetary increases to ensure Germany fulfills its NATO commitments and adequately strengthens its defense capabilities.",
        "SPD": "The SPD is divided on whether to increase the defense budget further. Though Defense Minister Boris Pistorius (SPD) has advocated for a \u20ac10 billion increase, citing the inadequacy of the existing \u20ac100 billion special fund to meet military needs, other prominent SPD figures like co-chair Saskia Esken have expressed skepticism about this proposal. The party appears cautious about balancing defense investments with other budgetary priorities and Germany's \"debt brake\" rule.",
        "FDP": "The FDP supports increased funding for the Bundeswehr to address current needs but has faced internal and coalition debates over the extent of budget increases. While Defense Minister Boris Pistorius and others have pushed for an additional \u20ac10 billion beyond the \u20ac100 billion \"Sonderverm\u00f6gen\" special fund, disagreements remain regarding prioritization and budget constraints, such as Germany\u2019s \"debt brake.\" Marie-Agnes Strack-Zimmermann, an FDP defense spokesperson, has emphasized that the existing funds are insufficient to meet modernization goals.",
        "GRUENE": "The Green Party (*B\u00fcndnis 90/Die Gr\u00fcnen*) has typically supported increasing defense spending under specific circumstances, aligning with Germany's \"Zeitenwende\" strategy for addressing security challenges after Russia's invasion of Ukraine. However, they emphasize that any budget increases for the Bundeswehr must be tied to efficiency reforms, transparency, and European cooperation. Internal debate exists within the party, with some members expressing reservations about significantly raising the defense budget further.",
        "LINKE": "Die LINKE would most likely oppose increasing the Bundeswehr's budget. Traditionally, the party advocates for disarmament and redirects military spending toward social and public welfare programs. This position aligns with their longstanding criticism of militarization and focuses on reducing conflicts through diplomacy.",
        "AFD": "The Alternative for Germany (AfD) has consistently opposed increasing the Bundeswehr's budget, criticizing current military spending as mismanaged and questioning the necessity of substantial defense expenditures. The party has frequently argued for prioritizing national sovereignty and border protection over expansive military projects or foreign intervention capabilities. While the AfD might support spending aimed exclusively at Germany's territorial defense, it is skeptical of large military budgets influenced by international commitments such as NATO."
    },
    2: {
        "CDU/CSU": "The CDU/CSU has supported the aim of achieving climate neutrality for Germany by 2045, as agreed under the existing framework. However, they generally emphasize balancing this goal with economic feasibility and protecting the competitiveness of German industries. While acknowledging the necessity of reducing emissions, the CDU/CSU advocates for pragmatic and technology-neutral approaches to achieve these objectives.",
        "SPD": "The SPD would likely affirm that Germany should continue pursuing the goal of becoming climate neutral. As outlined in their climate policies, they advocate for achieving climate neutrality by 2045 and have proposed measures such as reducing greenhouse gas emissions by 65% by 2030 (compared to 1990 levels) and 88% by 2040. This commitment is central to their long-term strategy for sustainable environmental and economic development.",
        "FDP": "The FDP supports the goal of achieving climate neutrality but advocates for a market-based and technology-neutral approach to climate policy. They emphasize enabling innovation and private-sector solutions rather than strict governmental regulations. Their stance typically opposes sector-specific targets and burdensome restrictions, favoring flexibility in achieving these goals.",
        "GRUENE": "B\u00fcndnis 90/Die Gr\u00fcnen (GR\u00dcNE) would strongly support Germany continuing its pursuit of becoming climate-neutral. They have consistently advocated for ambitious climate goals, including achieving net-zero greenhouse gas emissions by 2045, as outlined in Germany's Climate Protection Act. GR\u00dcNE also emphasize the importance of renewable energy expansion and stricter sector-specific CO2 reduction targets to meet this goal.",
        "LINKE": "Die Linke supports the goal of Germany reaching climate neutrality but emphasizes the need for strong social justice measures to accompany this transition. Their policies focus on a fair redistribution of costs, prioritizing low-income groups, and ensuring that the move towards climate neutrality does not exacerbate social inequality. They also advocate for significant public investments in renewable energy and public infrastructure to achieve this goal.",
        "AFD": "The AfD (Alternative for Germany) strongly opposes Germany's climate neutrality goals. The party typically argues against policies aimed at achieving climate neutrality, questioning their economic feasibility and scientific basis while advocating for less stringent climate measures. They often emphasize protecting traditional industries and reducing costs for citizens over pursuing ambitious environmental targets."
    },
    3: {
        "CDU/CSU": "Based on available context, the CDU/CSU is generally critical of increasing the CO2 tax in Germany. While the party recognizes the need for climate protection, its position emphasizes ensuring economic competitiveness and avoiding excessive financial burdens on citizens and businesses. The CDU/CSU typically advocates for balanced approaches, such as investing in technology and market-based solutions, rather than drastic tax increases.",
        "SPD": "The SPD is likely to support an increase in the CO2 tax as part of its commitment to achieving Germany's climate goals. Vice-Chancellor Olaf Scholz and former Environment Minister Svenja Schulze (both SPD) had previously introduced ambitious plans for reducing greenhouse gas emissions, including achieving climate neutrality by 2045. The party views such measures as vital for promoting generational justice and ensuring Germany's adherence to constitutional climate mandates.",
        "FDP": "The FDP has traditionally been critical of tax increases, including the CO2 tax, emphasizing market-based solutions and economic competitiveness. Former FDP leader Christian Lindner frequently opposed additional burdens on businesses and consumers via higher taxes. The party is likely to advocate for incentivizing technological innovation and efficiency over increasing the CO2 tax.",
        "GRUENE": "B\u00dcNDNIS 90/DIE GR\u00dcNEN (The Greens) would likely support raising the CO2 tax in Germany. The party consistently emphasizes ambitious climate policies and comprehensive emission reduction measures to combat climate change. Their platform traditionally advocates for economic incentives, such as higher CO2 pricing, to drive the transition towards renewable energy and sustainable practices.",
        "LINKE": "The LINKE (The Left) has consistently advocated for stronger climate policies, including measures to reduce greenhouse gas emissions. However, they generally emphasize that climate initiatives, such as a CO2 tax, should not disproportionately burden lower-income households. Their position would likely support increasing the CO2 tax only if it is accompanied by social compensation measures to protect affected populations.",
        "AFD": "The AfD (Alternative f\u00fcr Deutschland) generally opposes increases to the CO2 tax. The party's platform emphasizes skepticism toward climate policies that they believe disproportionately burden citizens and industry. They are likely to frame any CO2 tax hike as harmful to economic stability and household finances."
    },
    4: {
        "CDU/CSU": "CDU/CSU supports the continuation of border controls to manage migration and enhance security. The party has consistently advocated for stricter migration policies and stronger measures to prevent illegal crossings, emphasizing the need to maintain order and protect external EU borders. This is in line with their broader position on ensuring domestic safety and addressing migration challenges.",
        "SPD": "The SPD has not explicitly clarified its position on whether border controls should remain in place. However, Olaf Scholz's government has generally supported measures aligned with EU-level cooperation while balancing border security and free movement principles. For a definitive answer, their current manifesto or policy statements closer to the election would need to be consulted.",
        "FDP": "The FDP has generally supported maintaining border checks in targeted and temporary situations, particularly to ensure security and manage irregular migration effectively. However, the party emphasizes that this measure should not undermine the principle of open borders within the EU or Schengen agreements, advocating for long-term European solutions over indefinite national controls. These positions reflect the FDP's liberal approach to balancing security and European integration.",
        "GRUENE": "Based on the context provided, there is no direct mention of B\u00fcndnis 90/Die Gr\u00fcnen's (The Greens) official stance on maintaining border controls. However, The Greens generally advocate for open borders within the European Union and prioritize human rights, international cooperation, and European integration in their policies. If precise details from their 2025 manifesto are available, their position might be outlined there.",
        "LINKE": "Based on available information, Die LINKE (The Left) would likely oppose the continuation of border controls, as it has traditionally advocated for open borders and a more inclusive migration policy. Their stance generally aligns with criticism of policies perceived as restrictive or limiting freedom of movement within the EU. However, specific references to their position on current border controls in 2025 were not found in the provided context.",
        "AFD": "The AfD has historically supported stricter border controls and policies aiming to limit immigration. It is likely they would advocate for keeping border controls in place, citing national security and sovereignty. However, specific statements for the 2025 election would need to be referenced directly from their campaign materials or manifesto."
    }
}