questionnaire_party_answers = {
    0: {
        "SPD": "The SPD (Social Democratic Party of Germany) supports a balanced approach to aiding Ukraine in its conflict with Russia. They advocate for continued diplomatic, military, financial, and humanitarian assistance to Ukraine, emphasizing the need to support Ukraine's negotiations with Russia from a position of strength. The party aims to prevent a Russian-dictated peace treaty and uphold Ukraine's sovereignty and territorial integrity. While supporting the training of Ukrainian forces and the provision of weapons and equipment, the SPD stresses the importance of avoiding direct involvement in the war as a NATO member. They prioritize civilian support, recognizing the resilience of Ukraine's population as crucial to its defense. The SPD's stance aims to strike a balance between standing with Ukraine and preventing an escalation into a direct confrontation between NATO and Russia.",
        "CDU/CSU": "The CDU/CSU political party strongly advocates for increased military support for Ukraine. They believe that Ukraine's defense is crucial for Europe's security, as a potential fall of Ukraine could lead to further attacks on European countries. The party's stance is reflected in their commitment to providing Ukraine with all necessary means, including diplomatic, financial, humanitarian, and military aid. They aim to develop a joint strategy with key European allies and the US to support Ukraine's pursuit of peace and security. Additionally, the CDU/CSU proposes establishing a National Security Council to integrate foreign, security, defense, trade, and development policies. This comprehensive approach underscores their belief in the importance of a strong and united front in supporting Ukraine's sovereignty and freedom.",
    },
    1: {
        "SPD": "The SPD advocates for increased investments in security, particularly in the Bundeswehr, Germany's armed forces. They support a sustainable defense budget of at least 2% of the GDP, a significant increase from previous years. This budget aims to modernize the Bundeswehr and enhance Germany's defense capabilities. The party's stance is a response to the ongoing conflict in Ukraine, where Germany stands firmly with the invaded nation while seeking to prevent direct confrontation between NATO and Russia. Critics may argue that such a substantial budget increase could strain other public sectors, but the SPD emphasizes the need for a well-equipped European defense industry. They also propose expanding the Just Transition Fund to all industrial regions and strengthening public companies' capital bases.",
        "CDU/CSU": "The CDU/CSU party strongly advocates for a significant increase in the Bundeswehr budget, citing the need for a credible deterrent and the fulfillment of NATO capability goals. They propose an expansion of troop strength from 180,000 to 203,000 soldiers, emphasizing the Bundeswehr's role as a respected and integral part of society. The party's vision includes positioning the Bundeswehr as a leading European army in emerging technologies like space, drones, and cyber capabilities. Additionally, they plan to reform military and civilian structures to focus on the core military purpose and enhance infrastructure. Critics may argue that such a substantial budget increase could divert resources from other crucial areas, but the party's stance reflects a commitment to strengthening Germany's defense capabilities and its role within NATO.",
    },
}
