questionnaire_party_answers = {
    1: {
        "SPD": """The SPD (Social Democratic Party of Germany) advocates for the European Union (EU) to have the authority to impose its own taxes. They believe that this will make the EU financially independent of national governments and allow for more strategic investments in key EU policy areas. The party aims to reform the Multi-Annual Financial Framework to focus on policies with clear European added value. 

To achieve this, the SPD proposes introducing a financial transaction tax, similar to those in Paris and Milan, to make tax avoidance less attractive. They also support increasing taxes on high-value assets and capital income, with the revenue going towards strengthening and modernizing the education system. 

Critics argue that these measures may lead to a complex and potentially inefficient tax system, and there are concerns about the impact on businesses and investors. However, the SPD's focus on strategic value creation and resilience could enhance the EU's economic sovereignty.""",
        "CDU/CSU": """The CDU/CSU party opposes the EU's power to impose its own taxes, emphasizing the need for tax relief and the principle of subsidiarity. They argue that work should be rewarding and create prosperity, and thus, advocate for tax-free overtime pay and net pay increases for voluntary overtime. In times of crisis, the party proposes swift action by allowing for a rapid reduction in energy and sales taxes on essential goods without lengthy approval processes. Additionally, they support the idea of a European energy union, aiming to create a resilient energy market and reduce energy taxes for consumers. The party's stance is rooted in their belief that EU funds should be allocated to tasks that benefit European citizens and create added value.""",
    },
    2: {
        "SPD": """The SPD's stance on the future of combustion engine vehicles in the EU is multifaceted. They aim to support the automotive industry and maintain Germany's leading position in vehicle manufacturing. While advocating for better conditions for businesses to invest in Germany, the party also recognizes the need for a transition to electric mobility. To achieve this, they propose extending tax exemptions for electric cars until 2035 and improving the attractiveness of e-mobility through better depreciation conditions. The SPD plans to stimulate the purchase of electric vehicles, especially for private buyers, through tax incentives and subsidies. However, they also emphasize the importance of making the transition to electric vehicles accessible to all income groups and expect the EU Commission to take swift action on this matter.""",
        "CDU/CSU": """The CDU/CSU party advocates for a technology-driven approach to environmental and infrastructure policies. They aim to reverse the ban on combustion engine vehicles, arguing for a review of fleet emission standards and the prevention of penalties. The party supports the expansion of electric mobility infrastructure and promotes an open approach to alternative fuels and energy-efficient technologies. 

Their strategy includes streamlining bureaucratic processes and ensuring efficient training. They also emphasize the need for adequate financing of road and bridge infrastructure. The CDU/CSU's stance has been criticized for potentially hindering environmental progress, but they argue that their technology-focused approach will drive innovation and maintain Germany's competitiveness.""",
    },
    3: {
        "SPD": """The SPD advocates for a comprehensive approach to addressing the refugee crisis in the Mediterranean. They emphasize the legal obligation of search and rescue operations and criticize the criminalization of such efforts. The party proposes state-led EU initiatives, including safe and legal migration routes, resettlement programs, and humanitarian aid to prevent dangerous journeys. Additionally, the SPD supports EU resilience strategies, relocating key industries to Europe, and enhancing European defense capabilities through NATO. They aim to reform the EU's financial framework, prioritizing central policy areas, and promoting institutional reforms to enhance the union's effectiveness. The party's stance reflects a commitment to a stronger, more unified Europe, capable of addressing security challenges and upholding its values.""",
        "CDU/CSU": """The CDU/CSU party advocates for a stronger and more unified European security union, emphasizing the need for enhanced cooperation among member states in internal security matters. They propose developing Europol into a central hub for Europe, sharing data and information with national security agencies. The party also supports the principle of subsidiarity, ensuring EU funds are allocated to tasks that benefit European citizens and create added value. Regarding migration, they advocate for changing the European asylum law, suggesting that asylum seekers be transferred to safe third countries for processing. The party's stance on border control involves empowering Frontex, the EU's border and coast guard agency, with more personnel and authority to protect Europe's external borders jointly.""",
    },
    4: {
        "SPD": """The SPD (Social Democratic Party of Germany) strongly advocates for Ukraine's membership in the EU, emphasizing shared values and the protection of peace and freedom. They view EU expansion into Eastern Europe as a response to Russia's attempts at border expansion, and they support Ukraine's sovereignty and security interests. The party believes in a diplomatic approach, providing military, financial, and humanitarian aid to Ukraine in its fight against Russia's aggression. SPD also supports a bilateral security agreement with Ukraine and opposes any negotiations that undermine Ukraine's sovereignty. Additionally, they promote a stronger, unified Europe to address global challenges and protect democratic values, with a focus on human rights and the rule of law.""",
        "CDU/CSU": """The CDU/CSU party strongly supports Ukraine's EU membership, recognizing it as a strategic interest for Germany and Europe. They emphasize the need for Ukraine to meet all criteria before accession. The party proposes interim steps for candidate countries like Ukraine, which have not yet fulfilled all requirements but are committed to reforms. CDU/CSU advocates for supporting Ukraine's pursuit of peace, freedom, and security, including through NATO's role and providing diplomatic, financial, humanitarian, and military aid. They believe Ukraine's defense is crucial to preventing further attacks on European countries. While the party's stance is supportive, critics may argue that focusing on interim steps could delay full membership and that providing military aid could escalate tensions.""",
    },
    5: {
        "SPD": """The SPD's stance on ecological farming within the EU is multifaceted. They aim to reform agricultural subsidies, prioritizing support for farmers and promoting sustainable practices. The party believes in a balanced approach, acknowledging the potential for conventional farming to be environmentally friendly and efficient. Their strategy includes stabilizing energy prices to benefit farmers and ensuring regional development, especially in Eastern Germany. The SPD also emphasizes the need for digital transformation in agriculture, reducing bureaucracy, and protecting ecosystems. They support the EU's Clean Industrial Deal and advocate for a coordinated EU raw material strategy. Criticisms may arise regarding the balance between traditional and ecological farming methods and the potential impact on farmers' livelihoods.""",
        "CDU/CSU": """The CDU/CSU party's stance on the promotion of ecological agriculture within the EU is nuanced. They aim to achieve ecological goals through incentives, contract nature conservation, and rewarding nature and environmental protection. The party emphasizes the importance of both conventional and ecological agriculture, rejecting the compulsory idling of farmland. They advocate for a well-funded EU agricultural budget and a simplified Common Agricultural Policy (CAP) to reduce bureaucracy and increase efficiency for farmers. While supporting ecological initiatives, the CDU/CSU also prioritize the economic viability of agriculture, seeking to balance environmental goals with practical farming considerations. This approach has been criticized by some for potentially undermining ecological ambitions.""",
    },
    6: {
        "SPD": """The SPD's stance on the question of replacing the Euro with a national currency in Germany is not explicitly addressed in the provided document. However, the party's focus seems to be on strengthening Germany's economy and its position within the European Union. 

The SPD proposes creating a 'Deutschlandfonds', a fund to mobilize public and private capital for key investment needs, such as energy networks, hydrogen infrastructure, and housing. They aim to reduce bureaucracy and attract private investors. The party also advocates for a higher minimum wage, a reduction in VAT for food, and a stable pension system. 

Criticisms may arise regarding the potential impact of these policies on the European Union's monetary policy and the single market. The SPD's commitment to European integration and its plans to deepen the internal market could be seen as contradictory to the idea of a national currency.""",
        "CDU/CSU": """The CDU/CSU party in Germany has a clear stance on the Euro and national currency debate. They advocate for maintaining the Euro as the primary currency, emphasizing its role as a stability anchor for the Eurozone, particularly given Germany's economic strength. The party supports the introduction of a digital Euro but only if it provides genuine benefits, complements cash, and ensures financial stability, consumer privacy, and free usage. They prioritize financial stability and oppose any form of German liability for other countries' debts. Additionally, the CDU/CSU aims to enhance budget efficiency by eliminating ineffective spending, modernizing the federal budget, and focusing on goal-oriented fiscal management. This approach aims to prevent future crises and maintain a stable Euro currency system.""",
    },
    7: {
        "SPD": """The SPD's stance on gender identity and EU recommendations is progressive and inclusive. They aim to protect queer individuals from discrimination by explicitly including sexual orientation and gender identity in the German Constitution's anti-discrimination provisions. The party also supports the EU's recommendation to allow non-binary gender markers on passports, promoting gender-specific violence as a criminal offense across the EU. Additionally, the SPD advocates for the expansion of the EU to include Ukraine and Moldova, emphasizing shared values and peace. Their migration policy focuses on controlled migration and humanitarian standards for refugees. Critics may argue that their approach to migration is too restrictive, but the SPD's overall stance promotes equality and diversity, with a focus on improving healthcare access and research for vulnerable groups.""",
        "CDU/CSU": """The CDU/CSU party advocates for supporting countries on their path to EU membership, particularly those in the Western Balkans, Ukraine, and the Republic of Moldova, citing security and geopolitical interests. They propose interim steps for candidate countries that are committed to reforms but may not meet all accession requirements. The party also prioritizes strengthening worker mobility, simplifying cross-border employment procedures, and creating legal certainty to prevent false self-employment. Additionally, they emphasize the importance of language skills, particularly German, for successful integration. However, the CDU/CSU opposes the express naturalization process and dual citizenship, viewing the German passport as the culmination of integration rather than a starting point.""",
    },
    8: {
        "SPD": """The SPD's stance on wolf hunting is rooted in their commitment to protecting nature and ecosystems. They advocate for a balanced approach, allowing hunting in regions where wolf populations are not at risk. This decision is part of their broader strategy to preserve biodiversity and support regional economic structures. The party emphasizes the importance of sustainable agriculture and creating a harmonious coexistence between various industries and nature. While they promote the protection of wildlife and landscapes, the SPD also acknowledges the need for practical measures, such as allowing hunting to manage wolf populations effectively. This position has been criticized by some as a potential threat to wolf conservation, but the party stands by its decision, citing the importance of balancing ecological preservation with regional needs.""",
        "CDU/CSU": """The CDU/CSU party advocates for a balanced approach to wolf management, aiming for an "active population management." They propose regional hunting of wolves to reduce livestock predation, adapting the wolf's protection status and incorporating it into the Federal Hunting Act. This policy extends to other non-endangered species like crows and cormorants. The party emphasizes support for farmers and innovative, sustainable agriculture, promising to reduce bureaucratic burdens. Critics argue that this approach may disrupt ecological balance and question the need for hunting non-endangered species. The CDU/CSU's stance reflects a pragmatic attempt to manage wildlife while considering the interests of various stakeholders.""",
    },
    9: {
        "SPD": """The SPD party strongly advocates for a comprehensive energy transition and climate action plan. They propose mandatory photovoltaic installations for new residential buildings in the EU, emphasizing community involvement and decentralized energy supply. The party's key priorities include making communities climate-resilient, reducing energy costs for households and businesses, and promoting the adoption of electric vehicles and renewable energy sources. They aim to create a supportive framework for local heat planning, encouraging municipalities to adopt climate-friendly energy solutions. The SPD also focuses on making climate-friendly technologies more accessible and affordable, especially for low-income households. While their proposals aim to accelerate the energy transition, critics argue that some measures may not provide sufficient long-term planning security.""",
        "CDU/CSU": """The CDU/CSU party's stance on the question of mandatory photovoltaic installations in new residential buildings in the EU is twofold. On the one hand, they aim to make housing more affordable by simplifying building regulations and introducing a new building type, "Einfach," for cost-effective construction. They also propose temporary exceptions to planning laws for housing projects in tense markets. However, they also recognize the importance of energy efficiency and support the existing EH55 energy efficiency standard for new buildings, making it eligible for subsidies. The party's focus is on enabling homeownership, especially for families, by increasing income limits for existing incentive programs and including the purchase of existing properties.""",
    },
    10: {
        "SPD": """The SPD's stance on EU foreign policy decision-making is to move towards majority voting instead of unanimity. They argue that this will strengthen the EU's position globally, allowing it to speak with one voice and act more efficiently. The party believes that qualified majority voting will expedite negotiations, especially regarding trade agreements, and prevent individual member states from stalling progress. This shift is seen as a way to enhance Europe's sovereignty and unity, ensuring a more effective and democratic decision-making process. Critics may argue that this could lead to a loss of national sovereignty and influence, especially for smaller member states. However, the SPD emphasizes that this reform is necessary to address the challenges of an expanding EU and to maintain its global relevance.""",
        "CDU/CSU": """The CDU/CSU party advocates for a stronger and more unified European Union, emphasizing the importance of collective decision-making and a unified front. They propose enhancing European coordination, with a focus on finding common positions on critical issues. The party believes in the EU's strength when it acts as a cohesive unit, advocating for a reduction in bureaucratic processes and an increase in competitiveness. 

Additionally, they stress the need for a clear division of powers between the EU and its member states, ensuring a balanced approach to decision-making. The CDU/CSU aims for a Europe that is regionally rooted, nationally supported, and legitimately European, with a focus on representing its national interests strategically on the global stage.""",
    },
    11: {
        "SPD": """The SPD's stance on the question of tax-free jet fuel (Kerosin) for flights within the EU is twofold. Firstly, they aim to create a level playing field for German airports and airlines by advocating for a climate-neutral aviation sector. This includes transforming the air traffic tax into an EU climate levy, applicable to all airlines, including those from outside Europe. The party also supports research and the development of sustainable fuels for aviation. However, the SPD also recognizes the need for a pragmatic approach to EU-wide emissions targets. They argue that German automakers should not face penalties related to CO2 fleet limits, as these funds are crucial for investing in climate-friendly vehicles and securing jobs. This decision has been criticized for potentially hindering progress towards environmental goals.""",
        "CDU/CSU": """The CDU/CSU party advocates for maintaining a competitive aviation industry in Germany and the EU. They propose making kerosene, the primary aircraft fuel, tax-free for flights within the EU. This measure aims to reduce the overall costs of air travel, making it more affordable and sustainable. The party also emphasizes the need for quick relief during crises, advocating for flexible tax reduction on essential goods and energy. However, critics argue that tax exemptions for kerosene may hinder efforts to combat climate change and promote sustainable transportation. The CDU/CSU's stance on this issue reflects a balance between supporting the aviation industry and addressing economic challenges, while also facing scrutiny for its potential environmental impact.""",
    },
    12: {
        "SPD": """The SPD advocates for strengthening European alliances and cooperation, particularly in defense and security matters. They support expanding Europol's powers to combat environmental crimes and enhancing the role of the European Public Prosecutor's Office in this area. The party aims to foster a united European voice on the global stage and promote solidarity among member states, especially regarding the asylum system. Additionally, the SPD plans to initiate an effort to harmonize federal differences in police and assembly laws while strengthening federal and state police forces to protect the right to assembly. They emphasize the need for Europe to take on more responsibility for its security and uphold the values of the European peace project.""",
        "CDU/CSU": """The CDU/CSU party advocates for a stronger and more unified European security union, with a particular focus on enhancing the capabilities of Europol. They aim to foster closer cooperation between European states in matters of internal security. Key proposals include expanding Europol's role as a central hub for European security, with increased data-sharing and collaboration with national authorities. The party also supports strengthening Frontex, the European Border and Coast Guard Agency, by granting it sovereign powers and additional personnel. Additionally, they propose giving the Federal Police (Bundespolizei) greater powers to detain and detain individuals subject to deportation, especially those with criminal records or considered a threat. The party's stance on digital rights is controversial, as it advocates for extensive surveillance powers, including facial recognition and data analysis, which has drawn criticism from privacy advocates.""",
    },
    13: {
        "SPD": """The SPD's stance on EU-wide, multilingual public broadcasting is twofold. Firstly, they aim to reform the Multi-Annual Financial Framework (MFF) to prioritize key EU policies with clear European added value. This includes strengthening public broadcasting, which they view as a vital pillar of the media system. The party advocates for increased financial support for public broadcasters to provide high-quality, independent content for all generations. Additionally, the SPD supports private media companies through regulatory measures to ensure their stability and societal contribution. However, critics argue that this focus on media may divert attention from other crucial sectors. The party also emphasizes the importance of cultural accessibility and integration, proposing financial support for cultural infrastructure and inclusive strategies.""",
        "CDU/CSU": """The CDU/CSU party advocates for a reform of public-sector broadcasting (ÖRR) with a focus on independence, impartiality, and cost-effectiveness. They aim to ensure a media landscape that provides unbiased information, free from bias or one-sided perspectives. The party's key priorities include promoting cultural cooperation within Europe, strengthening cultural institutions, and supporting initiatives that remember the history of displacement and exile. Additionally, they emphasize the principle of subsidiarity, ensuring EU funds are allocated to create added value and benefit European citizens. Recent decisions include advocating for a reform of the Foreign Pension Act to address retirement disadvantages and supporting international cultural collaborations. Critics argue that their stance on media reform may limit the diversity of opinions and potentially restrict freedom of expression.""",
    },
    14: {
        "SPD": """The SPD political party strongly supports the EU's goal of becoming climate-neutral, advocating for a commitment to Germany's and the EU's climate targets. They aim to limit global temperature rise to well below 2 degrees Celsius and ideally achieve the 1.5-degree pathway. The party's climate policy focuses on preventing greenhouse gas emissions through renewable energy expansion, efficient energy management, industrial decarbonization, and a circular economy. 

The SPD proposes a community-oriented approach to climate policy, emphasizing solidarity and cost-effectiveness. They advocate for EU-wide measures, such as a climate levy on airlines and support for modernizing shipping fleets. The party also seeks to protect German industries, ensuring that climate-friendly production methods do not lead to job losses or competitive disadvantages.""",
        "CDU/CSU": """The CDU/CSU party advocates for a focused European Union, emphasizing tasks that are best addressed at the EU level. They propose abandoning the goal of climate neutrality, arguing for a regional and nationally driven Europe. The party's stance on climate change is notable, as they aim to meet the Paris Climate Goals by 2045 while ensuring economic competitiveness and social sustainability. This approach has been criticized for potentially compromising environmental goals. The party also seeks to avoid an EU soil law and amend the EU taxonomy for agriculture, reflecting their priority on national interests and economic stability. Their position on a stability union and rejecting German liability for other states' debts showcases a cautious financial approach.""",
    },
    15: {
        "SPD": """The SPD's stance on gender equality and representation in politics is a key focus of their policy agenda. They aim to achieve parity in German politics, with a 50/50 gender balance in all parliamentary and cabinet positions. The party plans to introduce a Parity Act to ensure equal representation in the Bundestag and promote equal participation in leadership roles. Additionally, the SPD supports an EU-wide women's rights charter and advocates for equal pay, aiming to implement the EU's Entgelttransparenzrichtlinie by 2026. Critics may argue that such measures could be seen as overly interventionist, but the SPD believes these steps are necessary to address gender inequality.""",
        "CDU/CSU": """The CDU/CSU party emphasizes the importance of a strong and unified Europe, prioritizing peace and freedom. They advocate for a realistic approach to EU enlargement, focusing on the performance and criteria of candidate countries. The party aims to strengthen Europe's internal and external capabilities through institutional reforms. Additionally, CDU/CSU supports a well-funded independent EU agricultural budget and seeks to simplify the Common Agricultural Policy (CAP) for farmers, reducing bureaucracy and increasing efficiency. They strongly oppose the Self-Determination Act, which allows minors to change their gender identity without professional assessment or court decision, emphasizing the need for child and youth protection over identity politics. Overall, the party's stance reflects a commitment to a competent and efficient Europe with a clear division of powers.""",
    },
    16: {
        "SPD": """The SPD (Social Democratic Party of Germany) advocates for a stronger social safety net and a more unified approach to social policies across the EU. They believe in setting European minimum standards for national basic income systems to combat poverty and ensure adequate social security. The party supports the Next Generation EU initiative, promoting sustainable investments and protecting the Eurozone from economic shocks through an EU unemployment reinsurance scheme. SPD also aims to establish gender-based violence as a criminal offense across the EU, with uniform standards for protection and prosecution. They advocate for a reformed Multiannual Financial Framework, focusing on core EU policies with clear European added value. A key priority is raising the minimum wage to at least 60% of the median income in Germany, in line with European guidelines.""",
        "CDU/CSU": """The CDU/CSU party takes a cautious approach to EU involvement in social security matters, emphasizing the principle of subsidiarity. They believe that EU funds should be allocated to tasks that provide a clear European benefit and advantage to its citizens. While they advocate for making Europe more resilient to crises, including establishing insolvency regulations for member states, the party opposes a European unemployment insurance scheme, considering employment policies as the domain of individual member states. The party's recent decisions include stricter enforcement of the obligations of social security recipients and the reintroduction of asset checks from the first day of receiving benefits, with the protected assets depending on the number of working years.""",
    },
    17: {
        "SPD": """The SPD's stance on social media platforms and their handling of disinformation is centered around transparency, accountability, and the protection of democratic discourse. They advocate for mandatory disclosure of algorithms and decision-making processes to prevent discrimination and manipulation. While supporting self-regulation, the party also emphasizes the need for state oversight to combat illegal content, systemic risks, and fake news. The SPD aims to foster media literacy and combat hate crimes and online offenses. They plan to expand programs promoting media and news literacy to counter manipulation and disinformation. Additionally, they will strengthen youth protection measures and combat all forms of human hostility, including online hate crimes and disinformation campaigns, by enhancing law enforcement capabilities.""",
        "SPD": "The SPD's stance on social media platforms and their handling of disinformation is centered around transparency, accountability, and the protection of democratic discourse. They advocate for mandatory disclosure of algorithms and decision-making processes to prevent discrimination and manipulation. While supporting self-regulation, the party also emphasizes the need for state oversight to combat illegal content, systemic risks, and fake news. The SPD aims to foster media literacy and combat hate crimes and online offenses. They plan to expand programs promoting media and news literacy to counter manipulation and disinformation. Additionally, they will strengthen youth protection measures and combat all forms of human hostility, including online hate crimes and disinformation campaigns, by enhancing law enforcement capabilities.",
        "CDU/CSU": "The CDU/CSU party advocates for increased transparency, combating disinformation, and ensuring youth protection on social media platforms. They prioritize children's and adolescents' safety online, viewing social media as essential platforms for exchange and information. The party's recent decisions include simplifying approval processes for public events and adapting data protection regulations for non-profit organizations, removing the requirement to appoint a data protection officer. Critics argue that these measures may lead to reduced oversight and potential risks, especially regarding data protection and youth safety. The party aims to balance trust in associations with necessary regulations, promoting a more entrepreneurial spirit while ensuring a strong social state.",
    },
    18: {
        "SPD": """The SPD's environmental policy focuses on expanding protected areas and implementing effective conservation measures. They advocate for the protection of forests, wetlands, and urban green spaces, aiming to create a harmonious coexistence between nature and various economic sectors. The party supports the designation of marine protected areas as genuine refuges for species. Additionally, the SPD emphasizes the fight against environmental crime, proposing the involvement of the European Public Prosecutor's Office and the expansion of Europol's resources in this field. 

On the topic of EU enlargement, the SPD expresses support for the accession of Ukraine and Moldova, viewing it as a statement against Russia's attempts at unilateral border changes. They also advocate for the swift integration of Western Balkan states into the EU, believing it will encourage progress and demonstrate the benefits of EU membership.""",
        "CDU/CSU": "The CDU/CSU party advocates for a balanced approach to land use and environmental protection within the EU. They prioritize the sustainable utilization of land and water areas, aiming to reduce land sealing and promote innovative dual or multiple land uses. The party's stance includes a focus on defending the rule of law in Europe, urging the EU Commission to take a more consistent approach to sanctioning member states for serious violations of fundamental values. They emphasize the importance of the EU's role in tasks that are better suited to the European level, advocating for a Europe that is regionally rooted, nationally supported, and legitimately European. However, the party's opposition to specific EU regulations, such as the substance flow balance in fertilizer law and the EU soil law, has been criticized for potentially hindering environmental protection efforts.",
    },
    19: {
        "SPD": "The SPD advocates for a strong and values-driven European Union, emphasizing the protection of EU principles and shared values. They propose a reform of the Multi-Annual Financial Framework, focusing on core EU policies with clear European added value. The party supports withholding EU funds from member states that violate EU rules and values, with a commitment to using existing legal instruments more consistently. Additionally, the SPD aims to enhance EU financial independence and strengthen human rights protection by joining the European Convention on Human Rights. However, they oppose blanket border closures, favoring a unified space of freedom and security. The party's stance reflects a balance between upholding EU values and ensuring practical measures for a functional union.",
        "CDU/CSU": "The CDU/CSU party advocates for a strong and unified European Union, emphasizing the importance of upholding its values and rules. They support the withholding of EU funds from member states that violate these principles, believing it to be an effective measure to defend European democracy. The party also prioritizes the Subsidiarity Principle, ensuring EU funds are allocated to projects that benefit European citizens and create added value. Additionally, they stand by the Stability and Growth Pact, advocating for strict adherence to its criteria and automated sanctions for violations. While recognizing the strategic importance of the Turkey-EU relationship, they express concern over Turkey's current distance from the EU's values. Overall, the CDU/CSU's stance reflects a commitment to a stable and values-driven European Union.",
    },
    20: {
        "SPD": "The SPD's stance on EU funding for Ukrainian weapons is nuanced. They support the idea of aiding Ukraine's defense and securing peace in Europe. However, they emphasize a balanced approach, ensuring Germany and NATO do not become direct parties to the conflict. The party advocates for a strong European defense industry and promotes innovation. While they recognize the importance of military support, they also highlight the need for civilian assistance, focusing on Ukraine's resilience and the protection of its population. SPD's long-term goal is a stable security order in Europe, utilizing platforms like the OSZE for mediation. This position aims to balance military aid with diplomatic efforts, reflecting a cautious yet supportive strategy towards Ukraine.",
        "CDU/CSU": "The CDU/CSU party strongly advocates for supporting Ukraine in its conflict with Russia. They believe that Ukraine's defense is crucial for European security, as its fall could lead to further attacks on other European nations. The party's stance includes providing Ukraine with all necessary means, including diplomatic, financial, humanitarian, and military aid. They aim to develop a joint strategy with key allies to support Ukraine's pursuit of peace and security. Additionally, CDU/CSU supports Ukraine's potential EU membership, considering it to be in the interest of Germany and Europe's security. Critics may argue that increased military aid could escalate the conflict, but the party stands firm in its belief that Ukraine's defense is essential for European stability.",
    },
}
