"""Init

Revision ID: 1b687584a068
Revises:
Create Date: 2025-09-20 23:25:22.575022

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b687584a068"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country_table",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.CHAR(length=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "party_table",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("country_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["country_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document_table",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "PDF",
                "DOCX",
                "XLSX",
                "PPTX",
                "MARKDOWN",
                "ASCII",
                "HTML",
                "XHTML",
                "CSV",
                name="supporteddocumentformats",
            ),
            nullable=False,
        ),
        sa.Column("party_id", sa.Uuid(), nullable=False),
        sa.Column("is_indexed", sa.Boolean(), nullable=False),
        sa.Column("is_manifesto", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_table")
    op.drop_table("party_table")
    op.drop_table("country_table")
    # ### end Alembic commands ###
