"""Add election table

Revision ID: 529b706d1db3
Revises: 1b687584a068
Create Date: 2025-09-22 10:25:08.326019

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "529b706d1db3"
down_revision: str | Sequence[str] | None = "1b687584a068"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "election_table",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("country_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["country_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("party_table", sa.Column("shortname", sa.String(), nullable=False))
    op.add_column("party_table", sa.Column("fullname", sa.String(), nullable=False))
    op.add_column("party_table", sa.Column("election_id", sa.Uuid(), nullable=False))
    op.drop_constraint(
        op.f("party_table_country_id_fkey"), "party_table", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "party_table", "election_table", ["election_id"], ["id"]
    )
    op.drop_column("party_table", "country_id")
    op.drop_column("party_table", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "party_table",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "party_table",
        sa.Column("country_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "party_table", type_="foreignkey")
    op.create_foreign_key(
        op.f("party_table_country_id_fkey"),
        "party_table",
        "country_table",
        ["country_id"],
        ["id"],
    )
    op.drop_column("party_table", "election_id")
    op.drop_column("party_table", "fullname")
    op.drop_column("party_table", "shortname")
    op.drop_table("election_table")
    # ### end Alembic commands ###
