"""Add created_at column

Revision ID: 614de782e806
Revises: 5a0e414c2c1b
Create Date: 2025-09-26 16:16:44.442216

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "614de782e806"
down_revision: str | Sequence[str] | None = "5a0e414c2c1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate_table",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "country_table",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.alter_column(
        "document_table", "indexing_sucess", new_column_name="indexing_success"
    )
    op.add_column(
        "document_table",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "election_table",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "party_table",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "proposed_question_table",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proposed_question_table", "created_at")
    op.drop_column("party_table", "created_at")
    op.drop_column("election_table", "created_at")
    op.alter_column(
        "document_table", "indexing_success", new_column_name="indexing_sucess"
    )
    op.drop_column("document_table", "created_at")
    op.drop_column("country_table", "created_at")
    op.drop_column("candidate_table", "created_at")
    # ### end Alembic commands ###
