"""Add proposed question and candidates

Revision ID: 62833ea4f61a
Revises: 529b706d1db3
Create Date: 2025-09-22 12:14:36.475980

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62833ea4f61a"
down_revision: str | Sequence[str] | None = "529b706d1db3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_table",
        sa.Column("given_name", sa.String(), nullable=False),
        sa.Column("family_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("party_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "proposed_question_table",
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("party_id", sa.Uuid(), nullable=False),
        sa.Column("cached_answer", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("election_table", sa.Column("year", sa.Integer(), nullable=False))
    op.add_column("election_table", sa.Column("date", sa.DateTime(), nullable=False))
    op.add_column("election_table", sa.Column("url", sa.String(), nullable=False))
    op.add_column("party_table", sa.Column("url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("party_table", "url")
    op.drop_column("election_table", "url")
    op.drop_column("election_table", "date")
    op.drop_column("election_table", "year")
    op.drop_table("proposed_question_table")
    op.drop_table("candidate_table")
    # ### end Alembic commands ###
