"""Remove is_manifesto column

Revision ID: 77979ce59457
Revises: 9f81ce6b3fc0
Create Date: 2025-09-23 15:56:31.020645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77979ce59457'
down_revision: Union[str, Sequence[str], None] = '9f81ce6b3fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_table', 'is_manifesto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_table', sa.Column('is_manifesto', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
