"""add_quiz_tables

Revision ID: 95072c6dbaad
Revises: bb2e3bfb28f2
Create Date: 2025-11-08 04:44:15.868585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95072c6dbaad'
down_revision: Union[str, Sequence[str], None] = 'bb2e3bfb28f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
