"""Init

Revision ID: 9f81ce6b3fc0
Revises:
Create Date: 2025-09-23 15:51:42.194101

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f81ce6b3fc0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country_table",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.CHAR(length=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "election_table",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("country_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["country_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "party_table",
        sa.Column("shortname", sa.String(), nullable=False),
        sa.Column("fullname", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("election_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["election_id"],
            ["election_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "candidate_table",
        sa.Column("given_name", sa.String(), nullable=False),
        sa.Column("family_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("party_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document_table",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "PDF",
                "DOCX",
                "XLSX",
                "PPTX",
                "MARKDOWN",
                "ASCII",
                "HTML",
                "XHTML",
                "CSV",
                name="supporteddocumentformats",
            ),
            nullable=False,
        ),
        sa.Column("party_id", sa.Uuid(), nullable=False),
        sa.Column("is_indexed", sa.Boolean(), nullable=False),
        sa.Column("is_manifesto", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "proposed_question_table",
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("party_id", sa.Uuid(), nullable=False),
        sa.Column("cached_answer", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("proposed_question_table")
    op.drop_table("document_table")
    op.drop_table("candidate_table")
    op.drop_table("party_table")
    op.drop_table("election_table")
    op.drop_table("country_table")
    # ### end Alembic commands ###
