"""add_cascade_delete_for_country_election_party

Revision ID: bb2e3bfb28f2
Revises: 130527b089b1
Create Date: 2025-10-30 06:33:35.178473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2e3bfb28f2'
down_revision: Union[str, Sequence[str], None] = '130527b089b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('candidate_table_party_id_fkey'), 'candidate_table', type_='foreignkey')
    op.create_foreign_key(None, 'candidate_table', 'party_table', ['party_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('document_table_party_id_fkey'), 'document_table', type_='foreignkey')
    op.create_foreign_key(None, 'document_table', 'party_table', ['party_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('election_table_country_id_fkey'), 'election_table', type_='foreignkey')
    op.create_foreign_key(None, 'election_table', 'country_table', ['country_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('party_table_election_id_fkey'), 'party_table', type_='foreignkey')
    op.create_foreign_key(None, 'party_table', 'election_table', ['election_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('proposed_question_table_party_id_fkey'), 'proposed_question_table', type_='foreignkey')
    op.create_foreign_key(None, 'proposed_question_table', 'party_table', ['party_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposed_question_table', type_='foreignkey')
    op.create_foreign_key(op.f('proposed_question_table_party_id_fkey'), 'proposed_question_table', 'party_table', ['party_id'], ['id'])
    op.drop_constraint(None, 'party_table', type_='foreignkey')
    op.create_foreign_key(op.f('party_table_election_id_fkey'), 'party_table', 'election_table', ['election_id'], ['id'])
    op.drop_constraint(None, 'election_table', type_='foreignkey')
    op.create_foreign_key(op.f('election_table_country_id_fkey'), 'election_table', 'country_table', ['country_id'], ['id'])
    op.drop_constraint(None, 'document_table', type_='foreignkey')
    op.create_foreign_key(op.f('document_table_party_id_fkey'), 'document_table', 'party_table', ['party_id'], ['id'])
    op.drop_constraint(None, 'candidate_table', type_='foreignkey')
    op.create_foreign_key(op.f('candidate_table_party_id_fkey'), 'candidate_table', 'party_table', ['party_id'], ['id'])
    # ### end Alembic commands ###
