"""Final

Revision ID: dae2d45bc33b
Revises: 7b214a5e445a
Create Date: 2025-09-23 23:00:28.312280

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'dae2d45bc33b'
down_revision: str | Sequence[str] | None = '7b214a5e445a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
