"""Any update?

Revision ID: ebff7e2802c5
Revises: dae2d45bc33b
Create Date: 2025-09-24 13:09:30.711143

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ebff7e2802c5"
down_revision: str | Sequence[str] | None = "dae2d45bc33b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
