questionnaire_party_answers = {
    1: {
        "SPD": """The SPD (Social Democratic Party of Germany) advocates for the European Union (EU) to have the authority to impose its own taxes. They believe that this will make the EU financially independent of national governments and allow for more strategic investments in key EU policy areas. The party aims to reform the Multi-Annual Financial Framework to focus on policies with clear European added value. 

To achieve this, the SPD proposes introducing a financial transaction tax, similar to those in Paris and Milan, to make tax avoidance less attractive. They also support increasing taxes on high-value assets and capital income, with the revenue going towards strengthening and modernizing the education system. 

Critics argue that these measures may lead to a complex and potentially inefficient tax system, and there are concerns about the impact on businesses and investors. However, the SPD's focus on strategic value creation and resilience could enhance the EU's economic sovereignty.""",
        "CDU/CSU": """The CDU/CSU party opposes the EU's power to impose its own taxes, emphasizing the need for tax relief and the principle of subsidiarity. They argue that work should be rewarding and create prosperity, and thus, advocate for tax-free overtime pay and net pay increases for voluntary overtime. In times of crisis, the party proposes swift action by allowing for a rapid reduction in energy and sales taxes on essential goods without lengthy approval processes. Additionally, they support the idea of a European energy union, aiming to create a resilient energy market and reduce energy taxes for consumers. The party's stance is rooted in their belief that EU funds should be allocated to tasks that benefit European citizens and create added value.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN supports granting the EU fiscal autonomy to finance environmental protection, social justice, and cross-border infrastructure. They argue that direct EU taxes reduce dependence on member states’ contributions. Critics fear it may increase bureaucracy, but the Greens maintain that transparent oversight and democratic control can ensure fair, effective distribution of funds across the Union.""",
        "FDP": """The FDP acknowledges the EU’s need for adequate funding but is cautious about introducing new taxes at the European level. They favor streamlined, market-oriented solutions to support growth. Critics argue this might limit the EU’s fiscal independence, but the FDP contends that competition and innovation can be better stimulated by minimizing tax burdens.""",
        "AfD": """The AfD firmly rejects any move allowing the EU to levy its own taxes, viewing it as a loss of national sovereignty. They argue that such measures undermine member states’ self-governance. Opponents claim this approach hampers coordinated investment in shared challenges, but the AfD insists national tax policy must remain independent.""",
        "DIE LINKE": """DIE LINKE supports an EU-wide tax framework, especially targeting large corporations and financial transactions to fund social programs. They see it as a tool for redistribution and reducing inequalities across member states. Critics fear economic disruptions, but the party contends that social cohesion and fair contributions outweigh potential risks.""",
        "FREIE WAEHLER": """FREIE WÄHLER holds a cautious stance on EU-level taxation, emphasizing subsidiarity and local fiscal autonomy. They recognize certain EU-wide efforts require stable financing but stress that member states should retain decision-making powers. Critics argue this limits the EU’s capacity to address shared priorities, yet the party prioritizes municipal independence.""",
        "Volt": """Volt strongly favors empowering the EU with its own tax system to boost pan-European initiatives in education, sustainability, and digital innovation. They believe this fosters unity and shared responsibility. Critics worry about shifting power away from national parliaments, but Volt emphasizes transparency and accountability mechanisms to maintain democratic oversight.""",
        "MLPD": """The MLPD sees EU taxation as a potential mechanism to challenge corporate power and fund social services, but remains skeptical of “capitalist EU structures.” They argue any new tax system must prioritize working-class interests. Critics doubt the feasibility of implementing such radical changes, but the MLPD promotes systemic transformation.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND acknowledges the need for adequate EU funding but remains uncertain about granting it full taxation rights. They call for clear conditions and democratic safeguards. Critics argue partial measures may be ineffective. The party stresses balancing national interests with European cooperation to ensure broad-based support.""",
        "BSW": """BSW is wary of the EU levying direct taxes, fearing bureaucratic expansion and complex regulations. They advocate for streamlined contributions through national governments. Proponents of EU taxation criticize this as too limited to tackle cross-border challenges. BSW stresses that any fiscal policy must prioritize member state autonomy and efficiency."""
    },

    2: {
        "SPD": """The SPD's stance on the future of combustion engine vehicles in the EU is multifaceted. They aim to support the automotive industry and maintain Germany's leading position in vehicle manufacturing. While advocating for better conditions for businesses to invest in Germany, the party also recognizes the need for a transition to electric mobility. To achieve this, they propose extending tax exemptions for electric cars until 2035 and improving the attractiveness of e-mobility through better depreciation conditions. The SPD plans to stimulate the purchase of electric vehicles, especially for private buyers, through tax incentives and subsidies. However, they also emphasize the importance of making the transition to electric vehicles accessible to all income groups and expect the EU Commission to take swift action on this matter.""",
        "CDU/CSU": """The CDU/CSU party advocates for a technology-driven approach to environmental and infrastructure policies. They aim to reverse the ban on combustion engine vehicles, arguing for a review of fleet emission standards and the prevention of penalties. The party supports the expansion of electric mobility infrastructure and promotes an open approach to alternative fuels and energy-efficient technologies. 

Their strategy includes streamlining bureaucratic processes and ensuring efficient training. They also emphasize the need for adequate financing of road and bridge infrastructure. The CDU/CSU's stance has been criticized for potentially hindering environmental progress, but they argue that their technology-focused approach will drive innovation and maintain Germany's competitiveness.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN strongly opposes allowing new combustion-engine vehicles after 2035. They advocate rapid electrification to reduce emissions, urging stronger EU-wide standards. Critics fear job losses, but the Greens stress that green tech investments create sustainable employment. They view a strict phase-out as essential for meeting climate targets and spurring innovation.""",
        "FDP": """The FDP is open to technological solutions, including synthetic fuels, rather than an outright ban on combustion engines. They seek to balance environmental goals with economic freedom. Critics claim this approach slows the transition to zero emissions, but the FDP argues that fostering innovation can lead to cleaner engines without restrictive regulations.""",
        "AfD": """The AfD rejects phasing out combustion vehicles, considering it an unnecessary restriction on consumer choice and industry. They argue the automotive sector remains critical to German prosperity. Opponents say this stance ignores climate imperatives. The party counters that modernizing traditional engines and promoting efficient fuels can reduce emissions without bans.""",
        "DIE LINKE": """DIE LINKE supports a robust transition to electric vehicles and calls for a post-2035 ban on new combustion cars. They emphasize social justice, advocating subsidies to make e-mobility affordable for low-income households. Critics warn of rapid industrial shifts, but the party sees it as vital for climate protection and equitable transport.""",
        "FREIE WAEHLER": """FREIE WÄHLER calls for flexible timelines and transitional arrangements for combustion engines post-2035. They support regional solutions reflecting local economic structures. Critics say this undermines a unified EU approach to climate targets. The party contends that innovation incentives and gradual change better protect jobs and regional industries.""",
        "Volt": """Volt favors a strict EU-wide phase-out of combustion engines by 2035 to accelerate decarbonization. They propose supporting manufacturers with green industrial strategies and retraining programs. Critics fear potential investment costs, but Volt believes a clear timeline spurs innovation, reduces pollution, and aligns Europe with global climate commitments.""",
        "MLPD": """The MLPD sees the phased ban on combustion engines as insufficient, calling for a broader transformation of the capitalist economy. They demand public ownership of key industries to ensure a just transition. Critics deem this unrealistic, but the party insists radical measures are needed to protect workers and the environment.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND questions a blanket ban on combustion engines, urging a balanced approach that includes alternative fuels and transitional solutions. Critics say this approach may delay climate progress. The party emphasizes targeted investments in research, aiming to reduce emissions while safeguarding the automotive sector’s competitiveness.""",
        "BSW": """BSW opposes a hard stop on new combustion vehicle registrations, arguing it risks consumer costs and job stability. They advocate for incremental targets and technology-neutral policies. Critics claim this is too lenient on polluters. BSW maintains that a gradual shift respects market forces and regional economic conditions."""
    },

    3: {
        "CDU/CSU": """The CDU/CSU acknowledges the humanitarian need for maritime rescue but prefers cooperation with existing EU agencies and member states rather than establishing a standalone entity. Critics argue this approach is too fragmented to address ongoing crises. The party contends that stronger border management, partnerships with origin countries, and targeted development aid can reduce migratory pressure.""",
        "SPD": """The SPD advocates for a comprehensive, EU-led search and rescue mission to prevent migrant deaths in the Mediterranean. They argue that a unified approach is more effective and reflects European solidarity. Opponents fear a pull factor encouraging more crossings. However, the SPD emphasizes that protecting human life must be the primary concern.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN strongly supports an EU-run rescue mission, viewing it as a moral obligation to save lives. They stress the importance of legal migration channels and fair asylum processes. Critics say this might encourage more arrivals. The Greens counter that humane treatment, responsibility-sharing, and stable solutions are essential to EU values.""",
        "FDP": """The FDP recognizes the need to save lives at sea but favors public-private cooperation over a purely EU-run service. They emphasize effective coordination with Frontex and NGOs. Critics worry this lacks consistent funding and oversight. The party believes flexible partnerships better manage resources while meeting humanitarian duties.""",
        "AfD": """The AfD opposes establishing an EU-led rescue service, fearing it could increase illegal migration by creating an incentive for dangerous journeys. They prefer stronger border controls and offshore processing. Critics denounce this stance as disregarding humanitarian principles. The AfD argues, however, that firm deterrence reduces overall migrant fatalities.""",
        "DIE LINKE": """DIE LINKE demands a well-funded EU sea rescue service under civilian command. They view saving lives as a legal and moral duty, advocating safe passage and humane reception for refugees. Detractors claim this exacerbates migratory pressures. The party insists solidarity and addressing root causes of flight should be Europe’s priority.""",
        "FREIE WAEHLER": """FREIE WÄHLER calls for a balanced approach, endorsing cooperation among EU states for rescue operations but hesitant about creating a large new agency. Critics say partial measures won’t adequately protect migrants. The party maintains that local strategies, development support in origin countries, and fair asylum processes must accompany rescue efforts.""",
        "Volt": """Volt strongly supports a dedicated EU maritime rescue program, arguing that shared responsibility is vital for a humane migration policy. They call for a legal framework ensuring transparency and cooperation. Opponents fear higher costs. Volt responds that a united approach avoids ad hoc crises and reflects core European values.""",
        "MLPD": """The MLPD advocates for a publicly controlled rescue force to protect migrants and challenges the EU’s “fortress” policies. Critics label this naïve, arguing it ignores practical constraints. The MLPD asserts that capitalist exploitation drives migration, demanding international solidarity and systemic change to end migration tragedies.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND proposes an EU coordination center to oversee search and rescue, favoring efficient collaboration instead of a new bureaucracy. Critics say this is insufficient for large-scale crises. The party stresses that targeted financial resources, legal pathways, and joint EU action can mitigate the root problems of migration.""",
        "BSW": """BSW is cautious about establishing a permanent EU rescue fleet. They emphasize supporting existing national forces and NGOs. Critics accuse them of underreacting to humanitarian emergencies. BSW contends that a decentralized approach, alongside meaningful development policies, can handle migrant flows while respecting each member state’s autonomy."""
    },

    4: {
        "CDU/CSU": """The CDU/CSU supports Ukraine’s European perspective but insists on stringent rule-of-law, economic, and anti-corruption reforms before membership. Critics say this stance delays crucial support. The party argues a thorough process maintains EU standards and stability, ensuring Ukraine’s readiness for the responsibilities of full membership.""",
        "SPD": """The SPD endorses Ukraine’s long-term path to EU membership, highlighting solidarity against external aggression and democratic reforms. Detractors worry about the EU’s capacity for further expansion. The SPD contends that supporting Ukraine strengthens European security and solidarity, provided that the accession process follows established criteria and benchmarks.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN strongly backs Ukraine’s EU aspirations, emphasizing democratic values and human rights. They believe rapid integration fosters regional stability. Critics fear haste could strain EU institutions. The Greens respond that a structured yet supportive approach bolsters Ukraine’s progress and secures Europe’s eastern borders.""",
        "FDP": """The FDP welcomes Ukraine’s closer ties to the EU, prioritizing reforms on transparency, governance, and market liberalization. Critics argue this demands extensive financial support. The FDP maintains that a prosperous, democratic Ukraine within the EU benefits both security and the single market, provided accession rules are respected.""",
        "AfD": """The AfD opposes Ukraine’s accession, citing the potential financial burden and geopolitical tensions with Russia. Critics claim this stance ignores Ukraine’s sovereignty and European aspirations. The AfD counters that further EU enlargement destabilizes existing structures and diverts resources from current member states.""",
        "DIE LINKE": """DIE LINKE supports Ukraine’s right to choose its alliances but remains cautious about fast-track EU membership amid ongoing conflict. They emphasize diplomacy and conflict resolution first. Critics argue that neutrality on this issue undermines solidarity. The party insists a peaceful, democratic Ukraine is the foundation for genuine EU integration.""",
        "FREIE WAEHLER": """FREIE WÄHLER acknowledges Ukraine’s European ambitions but urges a balanced approach. They warn that rapid accession risks uneven financial and social pressures on the EU. Critics say such caution weakens Ukraine. The party calls for targeted support and reform benchmarks to ensure a stable, well-prepared membership path.""",
        "Volt": """Volt strongly advocates for Ukraine’s membership, framing it as a bold step for European unity. They emphasize accelerated reforms and shared democratic values. Critics worry about the EU’s capacity to absorb new members. Volt contends inclusive expansion strengthens the EU’s global standing and commitment to freedom.""",
        "MLPD": """The MLPD criticizes both EU and NATO expansions as capitalist power plays, but supports the Ukrainian people’s right to self-determination. Critics find this position contradictory. The party insists genuine international solidarity, not EU membership, is needed to address underlying economic and political exploitation fueling the conflict.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND conditionally supports Ukraine’s candidacy, emphasizing the importance of institutional reforms and conflict resolution. Critics say this is too hesitant. The party argues that fulfilling EU criteria fosters stability, ensuring Ukraine can fully benefit from and contribute to the Union.""",
        "BSW": """BSW is wary of immediate expansion, calling for a thorough assessment of Ukraine’s readiness. Critics claim that postponing membership undermines Ukrainian sovereignty. BSW underscores that alignment with EU regulations and conflict de-escalation are prerequisites for any successful accession process."""
    },

    5: {
        "CDU/CSU": """The CDU/CSU supports promoting sustainable farming but emphasizes a balanced approach that accommodates conventional agriculture. Critics want stricter ecological mandates. The party contends voluntary incentives and innovation can improve environmental outcomes without undermining farmers’ competitiveness or increasing food prices.""",
        "SPD": """The SPD advocates stronger EU support for ecological agriculture, seeing it as key to climate protection and rural development. They propose subsidies and research funding. Some accuse them of ignoring cost increases for consumers. The SPD argues that greener practices protect long-term food security and benefit future generations.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN strongly endorses prioritizing organic and eco-friendly farming across the EU. They seek binding targets and robust financial incentives. Critics warn of higher costs and reduced yields. The Greens respond that sustainable farming preserves biodiversity, safeguards soil health, and meets escalating environmental challenges.""",
        "FDP": """The FDP is open to ecological farming measures but stresses market-based solutions and technological advancements rather than strict mandates. Critics say this is too lenient. The party argues flexible frameworks encourage innovation, ensuring farmers can adapt to consumer demands without excessive regulation.""",
        "AfD": """The AfD opposes granting exclusive priority to ecological farming, arguing it restricts choice and raises prices. Critics say ignoring environmental challenges damages long-term productivity. The party insists that diverse farming methods and reduced bureaucracy better serve national interests and food security.""",
        "DIE LINKE": """DIE LINKE supports robust funding for organic agriculture to reduce chemical use and protect small farmers. They also advocate fair market prices and stable incomes. Critics claim heavy regulations harm competitiveness. The party insists that public health, environmental protection, and rural livelihoods justify the shift toward sustainable methods.""",
        "FREIE WAEHLER": """FREIE WÄHLER encourages supporting ecological farming while allowing flexibility for regional specifics. Critics argue partial measures may not resolve climate impacts. The party contends that local decision-making, innovation incentives, and balanced EU funding can respect farmer autonomy and protect the environment.""",
        "Volt": """Volt prioritizes EU-wide ecological farming policies, aiming to harmonize standards and promote cutting-edge, green techniques. Critics warn uniform rules may overlook regional differences. Volt counters that coordinated strategies, research, and fair subsidies create synergy, scaling up sustainable practices for a healthier environment and more resilient food supply.""",
        "MLPD": """The MLPD calls for collective ownership of agribusiness, asserting that true ecological farming requires dismantling capitalist profit motives. Critics see this as extreme. The party maintains only a socialist approach can ensure long-term sustainability, free from corporate exploitation and harmful chemical practices.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND supports prioritizing eco-friendly farming but insists on transitional support and respect for market realities. Critics see this as slow progress. The party argues structured incentives, fair trade policies, and research help farmers adapt, balancing environmental benefits with economic stability.""",
        "BSW": """BSW is cautious about an overarching ecological mandate, fearing it could limit agricultural output and raise costs. Critics say it undervalues environmental obligations. BSW advocates moderate reforms that encourage eco-friendly practices but maintain competitive production levels across the EU."""
    },

    6: {
        "CDU/CSU": """The CDU/CSU firmly supports the Euro, dismissing calls to revert to a national currency. They argue the common currency fosters stability and trade. Critics of the Euro highlight sovereignty loss, but the CDU/CSU insists that economic benefits and Europe-wide cooperation outweigh any disadvantages.""",
        "SPD": """The SPD opposes reverting to a national currency, emphasizing the Euro’s role in facilitating EU integration and economic growth. Critics say monetary policy is too centralized. The SPD contends that shared fiscal instruments can mitigate crises more effectively than fragmented, national-level interventions.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN strongly rejects abandoning the Euro, seeing it as crucial for European unity and sustainable economic policy. Critics claim local interests are ignored. The Greens argue that monetary solidarity helps finance green investments and ensures resilience against global market fluctuations.""",
        "FDP": """The FDP defends the Euro as pivotal for an open single market. Critics argue it restricts monetary autonomy. The party believes that stable frameworks, rather than currency fragmentation, promote growth and investor confidence. They support reforms to strengthen EU-level monetary governance while upholding fiscal responsibility.""",
        "AfD": """The AfD advocates returning to a national currency, criticizing the Euro for creating unfair financial burdens and undermining sovereignty. Critics counter that leaving the Euro risks economic isolation. The party contends a reestablished Deutschmark or similar option would restore Germany’s full control over monetary policy.""",
        "DIE LINKE": """DIE LINKE generally supports the Euro but calls for broad reforms to address economic imbalances. They oppose a return to the Deutschmark, arguing that pan-European solidarity is vital for social justice. Critics say the Euro fosters austerity. The party asserts shared currency can work if accompanied by progressive fiscal policies.""",
        "FREIE WAEHLER": """FREIE WÄHLER is skeptical about fully abandoning the Euro, acknowledging potential disruptions. They suggest evaluating economic drawbacks and whether adjustments to EU monetary policy are more beneficial. Critics claim this ambivalence undermines confidence. The party emphasizes pragmatic solutions that address regional concerns without dismantling the single currency.""",
        "Volt": """Volt strongly opposes replacing the Euro, viewing it as a cornerstone of deeper European integration. Critics say smaller economies are overshadowed. Volt believes that robust EU institutions, not national currencies, best manage Europe’s shared challenges, from economic crises to cross-border sustainability efforts.""",
        "MLPD": """The MLPD dismisses the debate as a distraction from broader class struggles, criticizing the Euro as a tool for capitalist interests. While not advocating a national currency, they demand international worker solidarity. Critics see this as inconsistent. The MLPD insists real change requires transcending capitalist monetary systems altogether.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND defends the Euro’s role but calls for reforms ensuring fair financial burdens among member states. Critics accuse them of being indecisive about deeper integration. The party maintains that the Euro, with robust oversight, contributes to Europe’s competitiveness and shared prosperity.""",
        "BSW": """BSW is cautious about discarding the Euro, citing risks to exports and financial stability. Critics say they underestimate sovereignty issues. BSW concludes that while monetary policy must be improved, reverting to a national currency would disrupt trade, markets, and Germany’s position in Europe."""
    },

    7: {
        "CDU/CSU": """The CDU/CSU recognizes the need for respectful handling of gender identity but prefers national-level decision-making. Critics say this position hinders uniform rights. The party argues that cultural contexts vary, and an EU recommendation may not suit all member states equally.""",
        "SPD": """The SPD supports an EU recommendation to broaden gender identity options in passports, seeing it as a human rights issue. Critics warn of legal complexities across borders. The SPD contends that recognizing diversity fosters inclusivity and that uniform guidelines reduce administrative barriers for non-binary individuals.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN strongly back an EU-level push for inclusive identification, stating it affirms personal dignity and equal rights. Critics fear bureaucratic confusion. The Greens maintain that standardized recognition of diverse genders is essential for fairness and transnational consistency in the EU.""",
        "FDP": """The FDP is open to recommending non-binary passport options, favoring a liberal approach to individual freedom. Critics argue it complicates administrative systems. The FDP believes clear guidelines can accommodate all genders while minimizing bureaucratic hurdles, reflecting a modern understanding of identity.""",
        "AfD": """The AfD opposes extending official recognition to additional gender categories, describing such reforms as ideological. Critics deem this exclusionary. The party insists traditional gender definitions should remain the norm, arguing that multiple designations may erode societal consensus and create legal complexities.""",
        "DIE LINKE": """DIE LINKE fully endorses adding a third or non-binary option in passports, asserting that legal recognition is crucial for marginalized communities. Critics question cross-border compatibility. The party contends that human rights transcend administrative inconvenience and calls for EU-wide cooperation to standardize the approach.""",
        "FREIE WAEHLER": """FREIE WÄHLER believes in respecting personal identity choices but is cautious about imposing uniform solutions at the EU level. Critics see this as half-hearted support. The party emphasizes flexible frameworks that respect local traditions and legal systems while providing guidelines for broader gender recognition.""",
        "Volt": """Volt strongly champions an EU recommendation for inclusive gender markers, advocating a progressive, pan-European standard. Critics worry about cultural backlash. Volt argues that ensuring individual rights and dignity fosters a more cohesive, forward-thinking Europe, where personal identity is consistently recognized.""",
        "MLPD": """The MLPD supports expanded gender options, viewing it as part of the fight against discrimination. They criticize superficial reforms, however, calling for broader social change. Critics accuse them of using identity issues as a platform for revolutionary rhetoric. The MLPD insists systemic injustices must be confronted at every level.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND acknowledges the importance of recognizing diverse gender identities but prioritizes consultation with member states. Critics fear slow progress. The party argues that a well-coordinated EU recommendation, backed by local consensus, ensures lasting acceptance and minimal administrative conflict.""",
        "BSW": """BSW remains skeptical about EU-level directives on gender policy, advocating national autonomy. Critics argue this stifles equal rights across the Union. BSW holds that while individual freedom is crucial, uniform regulations may neglect regional nuances and overextend the EU’s mandate on civil matters."""
    },

    8: {
        "CDU/CSU": """The CDU/CSU supports managed wolf hunting where populations are stable and human-wildlife conflict is high, stressing rural interests. Critics fear it undermines conservation progress. The party argues regulated culls maintain balance, protect livestock, and reduce public tensions.""",
        "SPD": """The SPD proposes cautious licensing of wolf hunts, guided by scientific assessments to ensure sustainable populations. Some environmentalists criticize any culling. The SPD maintains that reconciling human activity with wildlife conservation requires flexible measures, including controlled hunts where risks to livestock or communities are significant.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN opposes wolf hunting except in strictly necessary cases, emphasizing non-lethal conflict prevention. Critics say this disregards farmers’ concerns. The Greens argue that robust herd protection, compensation, and habitat management reduce conflicts, while preserving a key predator’s ecological role.""",
        "FDP": """The FDP supports allowing hunting under clear criteria, advocating local decision-making. Critics warn that frequent exemptions could harm wolf recovery. The party believes targeted management can mitigate economic losses and regional tensions, provided strict oversight ensures that wolf populations remain healthy.""",
        "AfD": """The AfD favors liberalizing wolf hunting rules to protect farmers and prevent attacks. Conservationists accuse them of fearmongering. The party insists that culling is necessary to safeguard rural livelihoods, emphasizing national sovereignty in wildlife management over EU-protected status.""",
        "DIE LINKE": """DIE LINKE accepts limited culling as a last resort but prioritizes non-lethal solutions and robust compensation for farmers. Critics deem this approach too permissive or too restrictive. The party believes transparent guidelines can balance ecological needs with rural communities’ interests.""",
        "FREIE WAEHLER": """FREIE WÄHLER supports controlled wolf hunts where proven necessary, stressing that local authorities know regional conditions best. Critics worry about excessive local autonomy. The party argues practical solutions tailored to each area protect both wildlife and livelihoods, preventing overreach from centralized regulation.""",
        "Volt": """Volt backs science-based regulation that allows wolf hunting only if non-lethal methods fail and populations are secure. Critics demand stricter protections. Volt contends that a flexible, data-driven approach addresses regional challenges while preserving biodiversity, calling for EU coordination to share best practices.""",
        "MLPD": """The MLPD sees wolf culling as a symptom of broader environmental mismanagement. They demand collective farming methods that coexist with wildlife. Critics find such proposals impractical. The MLPD insists capitalist exploitation underlies conflicts with nature, advocating systemic change rather than targeted culls.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND supports conditional wolf hunting if population studies confirm it won’t endanger the species. Critics fear mismanagement. The party emphasizes that clear rules and monitoring ensure rural protection while upholding conservation goals, suggesting robust data collection to balance all interests.""",
        "BSW": """BSW endorses permitting wolf hunts under stringent guidelines, focusing on defending farms. Critics argue this could open the door to excessive kills. The party insists that regulated hunting remains a necessary tool, providing farmers with security and helping maintain acceptance of wolves in shared landscapes."""
    },

    9: {
        "CDU/CSU": """The CDU/CSU supports incentivizing solar installations but is hesitant about blanket mandates. Critics say voluntary measures aren’t enough for climate goals. The party argues that financial stimuli, not compulsory regulations, better encourage property owners to invest in photovoltaic technology.""",
        "SPD": """The SPD favors a requirement for photovoltaic systems on new buildings, citing climate targets and energy independence. Opponents fear higher construction costs. The SPD believes targeted subsidies, alongside regulations, can ensure affordability and accelerate the green energy transition.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN strongly advocates mandatory solar panels for new housing, seeing this as essential for a carbon-neutral future. Critics raise concerns about property rights. The Greens counter that common standards cut emissions, reduce energy bills, and foster renewable infrastructure.""",
        "FDP": """The FDP prefers market-driven expansion of solar energy, opposing universal mandates. Critics say this approach is too slow. The party argues that tax incentives and streamlined permitting create a more attractive environment for homeowners, stimulating renewable growth without burdensome directives.""",
        "AfD": """The AfD rejects compulsory solar installations, citing cost burdens and reduced personal freedom. Critics say ignoring green infrastructure imperils climate action. The party insists each country and homeowner should decide independently, trusting free-market forces over EU-imposed obligations.""",
        "DIE LINKE": """DIE LINKE supports making photovoltaic systems mandatory to combat climate change and lower energy bills. Critics warn of initial affordability barriers. The party proposes robust public funding and social housing programs to ensure equitable access to renewable energy solutions for all.""",
        "FREIE WAEHLER": """FREIE WÄHLER encourages renewable adoption but questions a universal EU mandate, arguing local conditions differ. Critics say voluntary schemes lack ambition. The party suggests flexible regulations paired with incentives, allowing communities to decide how best to expand solar power while respecting regional constraints.""",
        "Volt": """Volt strongly endorses mandatory photovoltaic requirements for new buildings, emphasizing EU-wide alignment. Critics worry about increased construction costs. Volt believes standardized rules drive innovation, scale economies, and sustainable growth, propelling Europe toward a climate-neutral future.""",
        "MLPD": """The MLPD views compulsory solar installations as a partial measure, insisting that broader revolutionary change is needed to truly address ecological crises. Critics find this unrealistic. The party argues capitalist profit motives stymie green technology adoption, and that socialist planning would yield more decisive progress.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND advocates mandatory solar solutions with transitional support for homeowners. Critics fear overregulation. The party maintains that clear rules, combined with financial assistance and technical guidance, ensure widespread compliance and accelerate the transition to clean energy in the building sector.""",
        "BSW": """BSW opposes an outright EU mandate, citing potential cost increases and bureaucratic hurdles. Critics say a voluntary approach won’t meet urgent climate goals. BSW stresses that subsidies, innovation incentives, and respect for regional contexts can effectively boost solar adoption without rigid obligations."""
    },

    10: {
        "CDU/CSU": """The CDU/CSU cautiously supports expanding qualified majority voting in some external policy areas but insists on retaining unanimity for core sovereignty issues. Critics argue this slows decisive action. The party believes a balanced approach preserves national interests while allowing the EU to respond effectively to global challenges.""",
        "SPD": """The SPD advocates broadening majority voting in foreign policy to strengthen the EU’s ability to act swiftly. Critics fear losing national veto rights. The SPD contends a more unified stance boosts Europe’s geopolitical influence and fosters solidarity among member states in times of crisis.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN strongly supports majority-based decision-making to overcome blockades, particularly on climate and human rights issues. Skeptics warn smaller states could be overridden. The Greens argue democracy is served by building consensus while enabling prompt, collective responses to global emergencies.""",
        "FDP": """The FDP favors a strategic expansion of majority voting, believing unanimous rules hamper timely EU action. Critics say it undermines national sovereignty. The party stresses that streamlined processes enhance Europe’s competitiveness on the world stage, though vital national interests must remain protected.""",
        "AfD": """The AfD rejects replacing unanimity, viewing it as a safeguard of national independence. Critics say this approach creates deadlocks. The party contends that foreign policy should remain under national control, warning majority voting could impose unwanted directives on member states.""",
        "DIE LINKE": """DIE LINKE supports majority decision-making if it advances peaceful, diplomatic initiatives. Critics fear centralizing power. The party maintains that democracy should be reinforced by a transparent, inclusive EU Parliament, ensuring foreign policy aligns with social and humanitarian priorities rather than militaristic agendas.""",
        "FREIE WAEHLER": """FREIE WÄHLER is hesitant about more majority voting, stressing each country’s right to shape its foreign affairs. Critics say this limits EU cohesion. The party believes compromise-based decisions, with input from all members, help preserve unity without marginalizing smaller or dissenting states.""",
        "Volt": """Volt strongly endorses extending qualified majority voting, arguing it’s essential for a more effective and unified EU voice on the global stage. Critics fear eroding national sovereignty. Volt believes democratic checks, such as a strong Parliament, can balance collective action and individual member state rights.""",
        "MLPD": """The MLPD denounces the EU’s foreign policy as imperialist, seeing the unanimity-versus-majority debate as irrelevant to workers’ interests. Critics say this ignores practical governance. The party demands dismantling militarist structures and forging global solidarity beyond EU institutions, which they consider capitalist.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND supports a targeted shift towards majority voting, noting it can resolve deadlocks on critical issues like sanctions. Critics warn of disenfranchising smaller states. The party argues that careful design of voting thresholds and opt-outs can protect sovereignty while enhancing the EU’s strategic capacity.""",
        "BSW": """BSW favors maintaining unanimity for pivotal decisions but is open to majority voting on less sensitive matters. Critics call this approach indecisive. BSW emphasizes preserving consensus where national security is at stake, while enabling more efficient processes for routine or shared-interest foreign policies."""
    },

    11: {
        "CDU/CSU": """The CDU/CSU supports maintaining tax exemptions on kerosene to protect aviation competitiveness and prevent flight shifts to non-EU hubs. Critics condemn the environmental impact. The party emphasizes parallel strategies, like alternative fuels, to reduce emissions without harming Europe’s airline industry.""",
        "SPD": """The SPD seeks to end kerosene tax exemptions, aligning aviation with other taxed energy sectors. Critics fear ticket price hikes. The party argues that taxing jet fuel motivates airlines to adopt cleaner technologies and fosters fair competition with greener transport options.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN strongly opposes kerosene tax breaks, citing climate change urgency. They propose EU-wide levies to fund environmental programs. Critics claim this burdens consumers. The Greens respond that pricing carbon fairly is crucial for shifting behavior and investing in sustainable transport alternatives.""",
        "FDP": """The FDP remains cautious about taxing kerosene, concerned about market distortions and competitive disadvantages. Critics say this stance delays climate progress. The FDP suggests incentivizing green aviation fuels and improving air traffic management, rather than imposing direct levies that could hamper economic growth.""",
        "AfD": """The AfD advocates continuing kerosene’s tax-free status to keep flights affordable and maintain industry jobs. Critics highlight the sector’s rising emissions. The party insists that investing in cleaner engines is more beneficial than taxation, which they view as an unfair burden on the economy.""",
        "DIE LINKE": """DIE LINKE calls for abolishing tax exemptions on kerosene, asserting polluters should bear environmental costs. Critics worry about effects on low-income travelers. The party believes revenue can fund eco-friendly transport infrastructure and that social measures could offset any disproportionate impact on ticket prices.""",
        "FREIE WAEHLER": """FREIE WÄHLER defends tax-free kerosene, fearing airlines would reroute or pass on costs to consumers. Critics accuse them of neglecting climate goals. The party prioritizes voluntary commitments and industry-led innovation, contending that abrupt tax changes risk economic harm without guaranteeing emissions cuts.""",
        "Volt": """Volt supports taxing kerosene to reflect its true environmental cost. Critics fear reduced mobility. Volt argues that consistent, EU-wide levies foster fair competition with rail and help finance sustainable alternatives. They believe harmonized regulations prevent uneven competitive conditions across Europe.""",
        "MLPD": """The MLPD opposes corporate privileges like untaxed kerosene and demands radical shifts away from air travel. Critics label this impractical. The party views the aviation sector as a prime example of capitalist excess, urging massive public investment in rail and green technology to replace flights.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND advocates a gradual reduction of kerosene’s tax privileges, allowing the aviation industry time to adapt. Critics say a slow approach delays meaningful change. The party contends that targeted measures, coupled with research into alternative fuels, can balance economic viability with environmental responsibility.""",
        "BSW": """BSW maintains kerosene should remain tax-free to protect competitiveness, especially for smaller airlines and regional airports. Critics argue climate imperatives trump business concerns. BSW suggests voluntary industry emissions targets and improved efficiency as more practical methods to lower aviation’s carbon footprint."""
    },

    12: {
        "CDU/CSU": """The CDU/CSU supports expanding Europol’s mandate to combat cross-border crime and terrorism, provided there are strong data protection safeguards. Critics worry about overreach. The party insists streamlined intelligence sharing is vital for security, arguing that well-defined legal frameworks will protect civil liberties.""",
        "SPD": """The SPD favors enhancing Europol’s powers, including investigative authority and data exchange, to tackle organized crime. Opponents warn of intrusive surveillance. The SPD sees coordinated policing as essential for modern threats, stressing parliamentary oversight to prevent abuses.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN are open to broader Europol competencies, with stringent privacy regulations and democratic accountability. Critics fear slowing down law enforcement. The Greens contend that strong transparency rules and oversight ensure efficient yet rights-respecting cooperation against transnational crime.""",
        "FDP": """The FDP endorses boosting Europol’s capacity for cross-border operations, focusing on organized crime and cyber threats. Critics raise privacy concerns. The party calls for robust oversight mechanisms and data protection, arguing an empowered Europol can bolster trust in EU-wide security measures.""",
        "AfD": """The AfD is wary of extending Europol’s authority, citing national sovereignty and fears of a supranational police force. Critics argue crime prevention needs EU collaboration. The party proposes closer intergovernmental cooperation instead of granting more power to an EU agency.""",
        "DIE LINKE": """DIE LINKE is cautious about strengthening Europol, highlighting the risk of excessive surveillance. Critics say this undermines EU security efforts. The party demands strict democratic control and an emphasis on social approaches to crime prevention, rather than merely expanding police powers.""",
        "FREIE WAEHLER": """FREIE WÄHLER supports measured increases in Europol’s role, advocating improved coordination rather than broad new authority. Critics say partial expansions may be ineffective. The party insists that national law enforcement remains primary, with Europol acting as a facilitating hub to handle cross-border issues.""",
        "Volt": """Volt strongly favors expanding Europol’s mandate to handle transnational challenges, from terrorism to cybercrime, under uniform standards. Critics worry about potential misuse of power. Volt believes transparent governance, real-time data sharing, and democratic checks are key to a more secure, unified Europe.""",
        "MLPD": """The MLPD opposes extending Europol’s powers, viewing it as a repressive instrument of capitalist states. Critics call this stance naive. The party asserts that increased policing won’t solve underlying social problems, arguing for systemic change rather than centralizing law enforcement across the EU.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND backs expanding Europol’s jurisdiction, especially against organized crime. Critics voice civil liberty concerns. The party emphasizes a clear legal basis for operations, urging robust parliamentary supervision to ensure citizens’ rights while improving cross-border cooperation.""",
        "BSW": """BSW is skeptical of granting Europol further powers, worried about potential centralization and bureaucratic overreach. Critics say this restricts Europe's ability to address pan-European crime. BSW proposes reinforcing existing cooperation frameworks and maintaining strict data-protection protocols rather than broadening Europol’s scope."""
    },

    13: {
        "CDU/CSU": """The CDU/CSU supports cross-border public broadcasting to strengthen cultural ties but is cautious about substantial funding increases. Critics say limited investment hampers European identity. The party emphasizes balancing costs and benefits, calling for efficient use of any additional resources.""",
        "SPD": """The SPD advocates enhanced funding for multilingual public media, believing it fosters mutual understanding and democratic discourse. Detractors question cost-effectiveness. The party argues that shared broadcasts enrich cultural exchange and counter misinformation, especially in politically sensitive topics.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN strongly favors more EU investment in public broadcasting that spans linguistic borders, promoting environmental and social awareness. Critics doubt the audience reach. The Greens maintain that diverse, accessible reporting helps shape a unified European public sphere.""",
        "FDP": """The FDP is open to expanding multilingual broadcasting but stresses cost-efficiency and clear performance metrics. Critics fear this approach discourages cultural depth. The party believes targeted funding can nurture cross-border cooperation, provided the programs remain innovative, market-friendly, and transparent in spending.""",
        "AfD": """The AfD opposes increased EU-level financing for public media, viewing it as propaganda that undermines national broadcasting autonomy. Critics say transnational coverage fosters European unity. The party argues members can manage their own media systems without supranational intervention.""",
        "DIE LINKE": """DIE LINKE supports robust EU funding for cross-border public broadcasting to promote social justice narratives and unbiased reporting. Critics worry about politicized content. The party insists that well-funded, multilingual public media empowers citizens to engage with international issues on an equal footing.""",
        "FREIE WAEHLER": """FREIE WÄHLER recognizes the value of shared media but remains hesitant about significant EU funding expansions. Critics say half measures weaken cultural integration. The party suggests more localized initiatives and partnerships, believing that local autonomy should shape content for cross-border programs.""",
        "Volt": """Volt strongly advocates a pan-European public broadcaster with increased funding. Critics question overlap with existing outlets. Volt argues multilingual content fosters continental identity and democratic engagement, especially for younger audiences. They see centralized yet transparent structures as essential for the network’s growth.""",
        "MLPD": """The MLPD rejects what it calls mainstream EU propaganda, viewing public media as an instrument of capitalist elites. Critics see this as an extreme stance. The party calls instead for grassroots communication networks and worker-run media, pushing for revolutionary perspectives beyond institutional outlets.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND backs moderate increases in funding to strengthen cross-border programming, focusing on news, culture, and education. Critics say more ambition is needed. The party insists on accountability measures to ensure public funds produce high-quality, multi-language content that resonates with diverse audiences.""",
        "BSW": """BSW questions additional financial support for EU-wide public broadcasting, arguing existing resources should be optimized first. Critics say this approach stalls European cultural exchange. The party maintains that media independence and efficiency matter more than large budgets, favoring targeted programs with clear goals."""
    },

    14: {
        "CDU/CSU": """The CDU/CSU opposes discarding climate neutrality, seeing it as integral to global responsibility. Critics say they’re slow on implementation. The party claims technology-driven solutions and balanced policies will maintain competitiveness while moving towards emissions reduction.""",
        "SPD": """The SPD rejects abandoning the climate neutrality goal, advocating a just transition to green industries. Some critics deem their approach too gradual. The party insists on strong social policies to protect workers, ensuring the shift doesn’t exacerbate inequality.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN firmly condemns any move to drop climate neutrality, framing it as a betrayal of future generations. Critics label their measures expensive. The Greens argue ambitious targets and decarbonization are vital for preserving ecosystems and global stability.""",
        "FDP": """The FDP maintains that climate neutrality is a critical target but should be pursued via market incentives and innovation, not strict bans. Critics question the feasibility. The party contends that competition spurs breakthroughs, making green solutions more practical and affordable.""",
        "AfD": """The AfD favors scrapping EU climate neutrality commitments, calling them costly and ineffective. Critics say this denial undermines urgent global efforts. The party argues national interests and economic growth should take precedence over supranational climate objectives.""",
        "DIE LINKE": """DIE LINKE strongly defends the net-zero goal, proposing expansive public investment to achieve it. Opponents warn about fiscal burdens. The party insists climate justice is non-negotiable and that collective action can transform energy systems for the common good.""",
        "FREIE WAEHLER": """FREIE WÄHLER does not support relinquishing the climate neutrality target but calls for pragmatic, region-specific strategies. Critics claim this weakens unified EU action. The party believes local contexts matter and that flexible timelines can reduce socio-economic disruptions.""",
        "Volt": """Volt vehemently rejects any plan to abandon climate neutrality, asserting it’s central to a forward-looking EU. Critics raise concerns about potential economic strain. Volt sees transformative environmental policies as a shared European project that catalyzes innovation and global leadership.""",
        "MLPD": """The MLPD dismisses half-measures, emphasizing radical eco-socialism over moderate climate neutrality goals. Critics label this utopian. The party claims capitalist structures are incapable of genuine environmental protection and demands systemic revolution to achieve meaningful ecological sustainability.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND opposes discarding the net-zero objective, advocating careful policy design to balance climate goals and economic realities. Critics say they lack urgency. The party argues that technology development and strategic investments can secure competitive, low-carbon growth.""",
        "BSW": """BSW supports continuing the climate neutrality aim but wants flexible benchmarks. Critics accuse them of diluting urgency. The party claims a measured approach, aligning industrial interests and environmental targets, ensures a smoother transition that citizens and businesses can afford."""
    },

    15: {
        "CDU/CSU": """The CDU/CSU endorses party autonomy in list composition, trusting voters to reward diversity. Critics demand binding quotas for gender parity. The party maintains internal measures to promote women, yet resists obligatory EU rules, citing principles of subsidiarity and democratic freedom.""",
        "SPD": """The SPD supports the freedom to decide but encourages robust gender quotas internally. Critics claim voluntary measures are too weak. The party argues balanced representation enriches democracy, and that gentle regulations can guide parties to ensure fair gender distribution on candidate lists.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN impose stringent internal quotas to guarantee gender equality. They welcome optional EU guidelines but prioritize self-imposed standards. Critics say quotas limit merit-based selection. The Greens maintain that structural inequalities require proactive intervention to achieve balanced representation.""",
        "FDP": """The FDP champions party-level autonomy over gender quotas, believing individuals should be chosen by merit. Critics argue women remain underrepresented. The party acknowledges the need for more female candidates but rejects top-down mandates, preferring mentorship and voluntary initiatives.""",
        "AfD": """The AfD firmly opposes mandatory quotas, labeling them social engineering. Critics accuse the party of deterring female participation. The AfD insists electoral lists should reflect natural candidate pools without artificial constraints, trusting the democratic process to yield fair outcomes.""",
        "DIE LINKE": """DIE LINKE advocates strong internal quotas to ensure gender-balanced lists but doesn’t push for a uniform EU rule. Critics claim universal regulations are necessary. The party holds that social movements, not top-down directives, best transform political culture toward equality.""",
        "FREIE WAEHLER": """FREIE WÄHLER supports voluntary approaches to improve women’s representation, resisting binding quotas. Critics say this leads to slow progress. The party contends that parties must retain autonomy to adapt methods that suit their grassroots structures, aiming for diversity without compulsory measures.""",
        "Volt": """Volt promotes gender parity on its lists, believing a modern democracy requires balanced voices. They do not demand an EU-wide mandate but encourage other parties to adopt similar standards. Critics fear over-regulation. Volt sees voluntary yet explicit commitments as key to fostering equal participation.""",
        "MLPD": """The MLPD denounces gender inequality as a capitalist symptom, supporting female leadership but rejecting tokenistic quotas. Critics find this contradictory. The party claims revolutionary empowerment of working-class women is the true path to gender equality, beyond bureaucratic list rules.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND respects parties’ right to decide on gender balance, encouraging internal solutions. Critics warn that voluntary measures rarely yield parity. The party believes respectful debate and incremental policy changes can enhance women’s representation without undermining party independence.""",
        "BSW": """BSW favors leaving gender ratio decisions to each party’s strategy, wary of top-down constraints. Critics say this perpetuates male dominance. The party contends democracy flourishes when diverse organizational cultures thrive, trusting that public scrutiny can hold parties accountable for fair representation."""
    },

    16: {
        "CDU/CSU": """The CDU/CSU opposes uniform EU mandates on social benefits, arguing socioeconomic diversity requires national approaches. Critics say this leaves inequalities unaddressed. The party maintains that subsidiarity ensures tailored solutions reflecting each country’s labor market and fiscal capacity.""",
        "SPD": """The SPD supports minimum standards for social security across the EU, ensuring a base level of dignity. Opponents claim this infringes on national sovereignty. The SPD argues coordinated policies reduce poverty and foster upward convergence, strengthening social cohesion in the single market.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN favors binding EU guidelines for social safety nets, seeing them as vital for fairness and solidarity. Critics worry about cost burdens for poorer states. The Greens counter that a common framework encourages upward harmonization, benefitting both people and economic stability.""",
        "FDP": """The FDP resists centralized mandates on welfare levels, preferring competition and national autonomy. Critics say this fosters a race to the bottom. The party insists flexible labor markets and targeted national reforms, not EU-imposed standards, better address varied social challenges.""",
        "AfD": """The AfD rejects any EU involvement in social security, asserting it’s a core national responsibility. Critics argue transnational disparities hurt European workers. The party counters that each state must design its own welfare system, free from EU interference, to preserve sovereignty.""",
        "DIE LINKE": """DIE LINKE calls for an EU-wide social floor, ensuring everyone meets a basic standard of living. Critics see it as financially unsustainable. The party asserts solidarity-based redistribution across the EU combats inequality and poverty, strengthening unity and social justice.""",
        "FREIE WAEHLER": """FREIE WÄHLER is cautious about uniform EU welfare rules, worried about overshadowing local conditions. Critics say minimal standards are vital to fairness. The party prefers flexible frameworks that guide member states without imposing rigid mandates, emphasizing regional solutions and budgetary discretion.""",
        "Volt": """Volt strongly supports establishing EU social baseline standards, believing it fosters equitable opportunities in all member states. Critics highlight economic diversity. Volt insists that strategic investments, shared resources, and common benchmarks enable a more cohesive and socially resilient Europe.""",
        "MLPD": """The MLPD claims minimal social floors under capitalism are insufficient, demanding a workers’ revolution to abolish inequalities. Critics dismiss this as extreme. The party asserts that EU reforms, while helpful, cannot address structural exploitation, urging broader class struggle for true social security.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND suggests a balanced EU framework for social guarantees, allowing national customization. Critics say this invites loopholes. The party contends partial harmonization can reduce wage dumping and protect living standards, ensuring each state can adapt rules to its economic realities.""",
        "BSW": """BSW opposes EU-imposed minimum welfare levels, fearing an overreach into national policy. Critics argue coordinated standards protect vulnerable citizens. The party believes that competition and decentralized governance better address local needs, though it accepts some EU guidance on best practices."""
    },

    17: {
        "CDU/CSU": """The CDU/CSU supports regulated self-governance for social networks, with possible legal interventions if harmful content persists. Critics say this defers responsibility to corporate interests. The party asserts collaboration between platforms and authorities, maintaining freedom of expression while combating severe misinformation.""",
        "SPD": """The SPD favors moderate regulation, holding platforms accountable for tackling disinformation. Critics warn about censorship. The party insists that voluntary corporate measures are insufficient and proposes clear legal standards, ensuring transparency and user protection without stifling legitimate debate.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN call for robust, transparent oversight, not just company discretion. Critics fear government overreach. The Greens maintain that misinformation threatens democratic discourse, requiring balanced regulatory frameworks and fact-checking mechanisms to preserve open discussion and public trust.""",
        "FDP": """The FDP advocates a light-touch approach, largely leaving content moderation to platforms. Critics say this fosters unchecked disinformation. The party argues user empowerment and transparency tools are preferable to state mandates, defending freedom of speech and innovation in digital markets.""",
        "AfD": """The AfD supports minimal interference, claiming platform-driven policies often censor conservative voices. Critics argue such laxity escalates false information. The party insists that rigorous debate, not regulatory intervention, counters misleading content, cautioning against big tech’s bias or government policing.""",
        "DIE LINKE": """DIE LINKE demands tighter oversight, fearing big tech firms prioritize profit over truth. Critics see potential free speech issues. The party advocates clear standards, user protection, and public interest fact-checking, contending that purely voluntary measures rarely address harmful disinformation effectively.""",
        "FREIE WAEHLER": """FREIE WÄHLER prefers platforms to set their own guidelines but supports external review for serious infractions. Critics question the efficacy of self-regulation. The party believes a mix of voluntary norms, public pressure, and legal recourse helps balance free expression with information integrity.""",
        "Volt": """Volt calls for EU-level regulations compelling social networks to act against disinformation while upholding user rights. Critics worry about bureaucracy. Volt argues a unified approach ensures consistent enforcement and fosters trust in online content, protecting democratic processes and diverse opinions.""",
        "MLPD": """The MLPD views mainstream platforms as instruments of capitalist narratives, advocating workers’ control over media. Critics find this unrealistic. The party claims big tech fails to curb disinformation benefiting corporate elites, insisting public ownership is needed for genuine freedom of information.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND backs a balanced model where platforms have autonomy but face stricter reporting obligations on their moderation practices. Critics say partial regulation might be ineffective. The party contends transparency can curb abuses and misinformation without stifling innovation or free speech.""",
        "BSW": """BSW prefers to let social media companies decide their moderation strategies, cautioning against rigid EU rules. Critics say tech firms are ill-equipped to prioritize public interest. The party contends that competition and user choice will pressure platforms to handle misinformation responsibly."""
    },

    18: {
        "CDU/CSU": """The CDU/CSU supports expanding protected areas but emphasizes local input to avoid harming economic activities. Critics say this slows ecological progress. The party argues well-managed conservation, coupled with sustainable land use, ensures both biodiversity and rural livelihoods.""",
        "SPD": """The SPD promotes increasing nature reserves as part of a broader environmental policy, citing the need to preserve habitats. Opponents fear agricultural constraints. The party believes responsible management and fair compensation can balance conservation with rural development.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN strongly advocates a substantial increase in protected areas, essential for biodiversity and climate resilience. Critics warn about land-use restrictions. The Greens assert that safeguarding ecosystems is critical for long-term sustainability, supporting farmers and communities through targeted assistance.""",
        "FDP": """The FDP endorses nature conservation but is wary of extensive designations that limit commercial usage. Critics see insufficient action for biodiversity. The party advocates flexible protection schemes and private incentives, prioritizing market-based approaches to harmonize ecological and economic interests.""",
        "AfD": """The AfD opposes large-scale expansions of protected areas, claiming overregulation restricts agriculture and development. Critics accuse them of neglecting environmental duties. The party insists local authorities should decide land use, emphasizing national sovereignty over EU conservation mandates.""",
        "DIE LINKE": """DIE LINKE supports significant expansion of protected zones, arguing that nature is a collective good. Critics say this impacts economic output. The party proposes public funding for affected communities, viewing biodiversity protection as a moral and social responsibility.""",
        "FREIE WAEHLER": """FREIE WÄHLER advocates a careful approach to designating new nature reserves, ensuring minimal economic disruption. Critics label this incrementalism as inadequate. The party stresses negotiation with local stakeholders, contending that acceptance is key to effective, enduring conservation efforts.""",
        "Volt": """Volt strongly backs expanding EU-wide protected areas and harmonizing environmental regulations. Critics question uniform rules across diverse regions. Volt counters that collaborative frameworks allow knowledge-sharing, ensuring consistent, high standards that protect biodiversity while accommodating local conditions.""",
        "MLPD": """The MLPD sees nature conservation as secondary to overthrowing capitalist exploitation, yet supports more protected areas if managed by workers’ councils. Critics reject mixing ecological aims with revolutionary rhetoric. The party insists capitalism fuels environmental damage, requiring fundamental social change to preserve nature.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND supports designating more nature reserves but emphasizes effective management and fair compensation for landowners. Critics fear bureaucratic expansion. The party believes balanced policies can sustain ecosystems and uphold property rights, fostering wider support for conservation.""",
        "BSW": """BSW is cautious about widespread new reserves, citing potential conflicts with farming and rural development. Critics argue urgent conservation needs are ignored. The party suggests targeted protection zones and economic incentives, believing cooperative approaches better reconcile environmental goals with local interests."""
    },

    19: {
        "CDU/CSU": """The CDU/CSU supports withholding funds from countries that breach the EU’s rule-of-law standards. Critics question the impact on citizens. The party argues it’s a necessary tool to uphold shared values and deter persistent violations, while urging fair procedures.""",
        "SPD": """The SPD endorses maintaining conditionality, believing it preserves democratic norms. Detractors say this punishes ordinary people. The party argues targeted measures motivate governments to comply with EU principles, safeguarding human rights and judicial independence.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN strongly backs tying funds to adherence to rule-of-law and civil liberties. Critics warn of deepening divisions. The Greens insist consistent enforcement is crucial for credibility, urging solidarity with citizens whose governments fail to meet EU standards.""",
        "FDP": """The FDP agrees in principle with withholding funds, but calls for clear, transparent criteria. Critics fear selective enforcement. The party contends that lawful, predictable oversight deters misconduct and fosters confidence in the EU’s commitment to democratic values.""",
        "AfD": """The AfD opposes withholding funds, claiming it interferes with national sovereignty. Critics argue that ignoring violations undermines EU unity. The party views financial penalties as overreach, preferring non-coercive dialogue to address constitutional or political disputes within member states.""",
        "DIE LINKE": """DIE LINKE supports conditionality to protect human rights, warning that enforcement must not harm vulnerable groups. Critics say governments may blame the EU for domestic failures. The party advocates complementary aid to civil society, ensuring that withholding funds isn’t misused politically.""",
        "FREIE WAEHLER": """FREIE WÄHLER backs linking aid to core EU principles but wants thorough investigations before withholding funds. Critics see potential for slow responses. The party insists that a fair, evidence-based process respects national complexities while defending democratic and legal norms.""",
        "Volt": """Volt strongly endorses withholding EU money from states violating shared values, seeing it as a vital enforcement mechanism. Critics worry about antagonizing certain governments. Volt argues robust conditionality fosters trust and unity, showing that European integration is rooted in fundamental rights.""",
        "MLPD": """The MLPD dismisses the EU’s sanctions approach, depicting it as political maneuvering among capitalist powers. Critics say this ignores real rule-of-law breaches. The party advocates grassroots solidarity instead, claiming top-down financial penalties do not address systemic exploitation or class struggles.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND agrees with withholding funds for clear violations, emphasizing standardized procedures to avoid politicization. Critics worry about punishing citizens. The party suggests parallel support for NGOs and independent institutions, ensuring that penalties are targeted at uncooperative governments.""",
        "BSW": """BSW questions the effectiveness of withholding funds, cautioning it might fuel Euroskeptic sentiment in targeted states. Critics say unconditional aid rewards bad governance. The party proposes a balanced approach, prioritizing dialogue yet keeping financial pressure as a last resort measure."""
    },

    20: {
        "CDU/CSU": """The CDU/CSU supports increasing military assistance to Ukraine for self-defense, within a coordinated EU framework. Critics fear escalation. The party argues that credible deterrence, alongside diplomatic efforts, is necessary to uphold European security and international law.""",
        "SPD": """The SPD endorses limited, responsible arms funding to Ukraine, balancing solidarity with diplomacy. Critics say hesitancy weakens Ukraine’s position. The party insists defensive aid must be paired with humanitarian and negotiation initiatives to foster a lasting resolution.""",
        "GRUENE": """BÜNDNIS 90/DIE GRÜNEN, after initial hesitations, now back military aid to Ukraine, citing human rights and sovereignty. Critics accuse them of abandoning pacifist roots. The Greens maintain that support is necessary to protect civilians, though they emphasize conflict de-escalation through diplomacy.""",
        "FDP": """The FDP advocates robust EU backing for Ukraine’s defense, arguing that a strong stance deters aggression. Critics fear an arms race. The party contends that credible military support, combined with political solutions, is essential for stability and upholding international norms.""",
        "AfD": """The AfD opposes further EU weapons financing, warning of entangling Germany in foreign conflicts. Critics say this neglects Ukrainian sovereignty. The party calls for neutrality and diplomacy, suggesting that armed involvement deepens tensions and drains resources needed at home.""",
        "DIE LINKE": """DIE LINKE is deeply skeptical of increased arms funding, citing the party’s anti-war ethos. Critics say it’s naive amid aggression. The party urges negotiations and humanitarian solutions, fearing militarization only prolongs conflict, harming civilians and risking broader confrontation.""",
        "FREIE WAEHLER": """FREIE WÄHLER cautiously supports limited arms financing under strict controls. Critics say partial measures risk inefficiency. The party insists that any military aid must be accompanied by diplomatic engagement, ensuring accountability and preventing uncontrolled escalation of the conflict.""",
        "Volt": """Volt strongly favors increased EU military assistance for Ukraine, viewing it as a defense of European values. Critics fear drawing the EU into a larger war. Volt emphasizes that robust deterrence and unity among member states can foster negotiations leading to a just peace.""",
        "MLPD": """The MLPD rejects arms financing, describing it as fueling capitalist power struggles. Critics accuse them of abandoning Ukraine. The party denounces both NATO expansion and Russian aggression, insisting that workers on all sides need international solidarity instead of further militarization.""",
        "BÜNDNIS DEUTSCHLAND": """BÜNDNIS DEUTSCHLAND supports additional funding for defensive weapons, arguing that Ukraine’s sovereignty is a European concern. Critics worry about escalation. The party contends coordinated EU policy, combined with diplomacy, sends a strong signal of unity and deterrence against external aggression.""",
        "BSW": """BSW remains uncertain about providing more arms, citing unpredictability of conflict. Critics say indecision undermines EU solidarity. The party suggests focusing on economic support and negotiations, fearing further militarization could escalate tensions beyond Ukraine’s borders."""
    }
}
default_party_info = {
    "SPD": "Social democratic party focusing on workers' rights and social welfare",
    "GRUENE": "Environmental party advocating for climate action and sustainability",
    # ... other parties
    "Tierpartei": "Animal protection and environmental sustainability focused",
    "Piratenpartei": "Focuses on digital rights and government transparency"
}